import type { ClinicSessionListItem } from '../model/types';
import type { ClinicStudentRow } from '@/entities/member';

export const MOCK_CLINIC_SESSIONS: ClinicSessionListItem[] = [
  { id: 's1', timeSlot: '09:00 - 10:00', enrolled: 3 },
  { id: 's2', timeSlot: '10:00 - 11:00', enrolled: 4 },
  { id: 's3', timeSlot: '11:00 - 12:00', enrolled: 2 },
  { id: 's4', timeSlot: '13:00 - 14:00', enrolled: 3 },
];

export const MOCK_SESSION_STUDENTS: Record<string, ClinicStudentRow[]> = {
  s1: [
    {
      id: 1,
      nameKo: '김민수',
      nameLastEn: 'Kim',
      nameFirstEn: 'Minsu',
      grade: 11,
      assignedLevel: 7,
      assignedWordCount: 50,
      testQuestionCount: 30,
      testConfig: { type: 'word-to-meaning', includeSynonyms: true },
      memos: [
        { id: 1, date: '2026.04.08', content: '단어 암기 속도가 빠름.' },
        { id: 2, date: '2026.04.01', content: '고급 어휘 위주 학습 권장.' },
      ],
      latestMemoContent: '단어 암기 속도가 빠름.',
    },
    {
      id: 2,
      nameKo: '이영희',
      nameLastEn: 'Lee',
      nameFirstEn: 'Younghee',
      grade: 9,
      assignedLevel: 3,
      assignedWordCount: 30,
      testQuestionCount: 20,
      testConfig: { type: 'word-to-meaning', includeSynonyms: false },
      memos: [{ id: 3, date: '2026.04.07', content: '재시험 예정.' }],
      latestMemoContent: '재시험 예정.',
    },
    {
      id: 3,
      nameKo: '박지민',
      nameLastEn: 'Park',
      nameFirstEn: 'Jimin',
      grade: 12,
      assignedLevel: 5,
      assignedWordCount: 40,
      testQuestionCount: 25,
      testConfig: { type: 'meaning-to-word', includeSynonyms: false },
      memos: [],
      latestMemoContent: null,
    },
  ],
  s2: [
    {
      id: 4,
      nameKo: '최수연',
      nameLastEn: 'Choi',
      nameFirstEn: 'Suyeon',
      grade: 10,
      assignedLevel: 4,
      assignedWordCount: 40,
      testQuestionCount: 25,
      testConfig: { type: 'word-to-meaning', includeSynonyms: true },
      memos: [],
      latestMemoContent: null,
    },
    {
      id: 5,
      nameKo: '정도현',
      nameLastEn: 'Jung',
      nameFirstEn: 'Dohyun',
      grade: 11,
      assignedLevel: 8,
      assignedWordCount: 50,
      testQuestionCount: 30,
      testConfig: { type: 'word-to-meaning', includeSynonyms: true },
      memos: [{ id: 4, date: '2026.04.09', content: '집중력 좋음.' }],
      latestMemoContent: '집중력 좋음.',
    },
    {
      id: 6,
      nameKo: '강지수',
      nameLastEn: 'Kang',
      nameFirstEn: 'Jisu',
      grade: 10,
      assignedLevel: 2,
      assignedWordCount: 30,
      testQuestionCount: 20,
      testConfig: { type: 'word-to-meaning', includeSynonyms: false },
      memos: [
        { id: 5, date: '2026.04.05', content: '기초 어휘 보완 중.' },
        { id: 6, date: '2026.03.28', content: '발음 교정 필요.' },
      ],
      latestMemoContent: '기초 어휘 보완 중.',
    },
    {
      id: 7,
      nameKo: '오세훈',
      nameLastEn: 'Oh',
      nameFirstEn: 'Sehun',
      grade: 9,
      assignedLevel: 1,
      assignedWordCount: 20,
      testQuestionCount: 15,
      testConfig: { type: 'word-to-meaning', includeSynonyms: false },
      memos: [],
      latestMemoContent: null,
    },
  ],
  s3: [
    {
      id: 8,
      nameKo: '한소희',
      nameLastEn: 'Han',
      nameFirstEn: 'Sohee',
      grade: 11,
      assignedLevel: 6,
      assignedWordCount: 50,
      testQuestionCount: 30,
      testConfig: { type: 'meaning-to-word', includeSynonyms: true },
      memos: [],
      latestMemoContent: null,
    },
    {
      id: 9,
      nameKo: '송미래',
      nameLastEn: 'Song',
      nameFirstEn: 'Mirae',
      grade: 10,
      assignedLevel: 4,
      assignedWordCount: 40,
      testQuestionCount: 20,
      testConfig: { type: 'word-to-meaning', includeSynonyms: false },
      memos: [],
      latestMemoContent: null,
    },
  ],
  s4: [
    {
      id: 10,
      nameKo: '임채원',
      nameLastEn: 'Lim',
      nameFirstEn: 'Chaewon',
      grade: 10,
      assignedLevel: 5,
      assignedWordCount: 40,
      testQuestionCount: 25,
      testConfig: { type: 'word-to-meaning', includeSynonyms: false },
      memos: [{ id: 7, date: '2026.04.08', content: '중간고사 대비 집중 학습 필요.' }],
      latestMemoContent: '중간고사 대비 집중 학습 필요.',
    },
    {
      id: 11,
      nameKo: '윤재혁',
      nameLastEn: 'Yoon',
      nameFirstEn: 'Jaehyuk',
      grade: 12,
      assignedLevel: 9,
      assignedWordCount: 60,
      testQuestionCount: 35,
      testConfig: { type: 'word-to-meaning', includeSynonyms: true },
      memos: [{ id: 8, date: '2026.04.06', content: '심화 과정 진행 중.' }],
      latestMemoContent: '심화 과정 진행 중.',
    },
    {
      id: 12,
      nameKo: '박지민',
      nameLastEn: 'Park',
      nameFirstEn: 'Jimin',
      grade: 12,
      assignedLevel: 5,
      assignedWordCount: 40,
      testQuestionCount: 25,
      testConfig: { type: 'meaning-to-word', includeSynonyms: false },
      memos: [{ id: 14, date: '2026.04.04', content: '꾸준한 성적 향상.' }],
      latestMemoContent: '꾸준한 성적 향상.',
    },
  ],
};
