import type { ClinicCycle } from '@/entities/clinic';
import type { TestBundle } from '../model/types';

export const MOCK_CYCLES: TestBundle[] = [
  {
    id: '1',
    assignedLevel: 7,
    wordCount: 50,
    steps: [
      { key: 'word', label: 'Word', status: 'waiting', totalScore: '100' },
      { key: 'sentence', label: 'Sentence', status: 'available', totalScore: '100' },
      { key: 'review1', label: 'Review 1', status: 'grading', totalScore: '100' },
      {
        key: 'review2',
        label: 'Review 2',
        status: 'passed',
        scores: ['98'],
        totalScore: '100',
        gradedDate: '23.10.23',
      },
      {
        key: 'review3',
        label: 'Review 3',
        status: 'fail',
        scores: ['62'],
        totalScore: '100',
        gradedDate: '23.10.24',
      },
    ],
  },
  {
    id: '2',
    assignedLevel: 3,
    wordCount: 47,
    steps: [
      { key: 'word', label: 'Word', status: 'fail', scores: ['62'], totalScore: '100' },
      { key: 'sentence', label: 'Sentence', status: 'locked' },
      { key: 'review1', label: 'Review 1', status: 'locked' },
      { key: 'review2', label: 'Review 2', status: 'locked' },
      { key: 'review3', label: 'Review 3', status: 'locked' },
    ],
  },
  {
    id: '3',
    assignedLevel: 5,
    wordCount: 30,
    steps: [
      {
        key: 'word',
        label: 'Word',
        status: 'passed',
        scores: ['95'],
        totalScore: '100',
        gradedDate: '23.09.10',
      },
      {
        key: 'sentence',
        label: 'Sentence',
        status: 'passed',
        scores: ['55', '88'],
        totalScore: '100',
        gradedDate: '23.09.11',
      },
      {
        key: 'review1',
        label: 'Review 1',
        status: 'passed',
        scores: ['60', '72', '92'],
        totalScore: '100',
        gradedDate: '23.09.12',
      },
      {
        key: 'review2',
        label: 'Review 2',
        status: 'passed',
        scores: ['96'],
        totalScore: '100',
        gradedDate: '23.09.13',
      },
      {
        key: 'review3',
        label: 'Review 3',
        status: 'passed',
        scores: ['100'],
        totalScore: '100',
        gradedDate: '23.09.14',
      },
    ],
  },
];

export const MOCK_CLINIC_CYCLES: ClinicCycle[] = [
  {
    title: 'Cycle #48-97',
    badge: 'High Priority',
    scheduledDate: '23.10.23',
    steps: [
      {
        key: 'word',
        label: 'Word',
        status: 'pending',
        date: '23.10.24',
        totalScore: '30',
        testType: 'meaning-to-word',
      },
      {
        key: 'sentence',
        label: 'Sentence',
        status: 'active',
        date: '23.10.24',
        totalScore: '30',
        testType: 'meaning-to-word',
      },
      {
        key: 'review1',
        label: 'Review 1',
        status: 'passed',
        date: '23.10.23',
        scores: ['98'],
        totalScore: '100',
        testType: 'meaning-to-word',
      },
      {
        key: 'review2',
        label: 'Review 2',
        status: 'fail',
        date: '23.10.24',
        scores: ['62'],
        totalScore: '100',
        testType: 'meaning-to-word',
      },
      {
        key: 'review3',
        label: 'Review 3',
        status: 'passed',
        date: '23.10.25',
        scores: ['55', '75', '88'],
        totalScore: '100',
        testType: 'meaning-to-word',
      },
    ],
  },
  {
    title: 'Cycle #01-47',
    badge: 'Standard',
    scheduledDate: '23.10.24',
    steps: [
      {
        key: 'word',
        label: 'Word Test',
        status: 'fail',
        date: '23.10.24',
        scores: ['62'],
        totalScore: '100',
        isPassed: false,
        testType: 'meaning-to-word',
      },
      {
        key: 'sentence',
        label: 'Sentence',
        status: 'locked',
        testType: 'meaning-to-word',
        subLabel: 'Locked',
      },
      {
        key: 'review1',
        label: 'Review 1',
        status: 'locked',
        testType: 'meaning-to-word',
        subLabel: 'Locked',
      },
      {
        key: 'review2',
        label: 'Review 2',
        status: 'locked',
        testType: 'meaning-to-word',
        subLabel: 'Locked',
      },
      {
        key: 'review3',
        label: 'Review 3',
        status: 'locked',
        testType: 'meaning-to-word',
        subLabel: 'Locked',
      },
    ],
  },
];
