import type { WordTestItem, VocabReviewItem } from '@/entities/word';

type WordTestAnswer = { answer: string; synonym: string };

export const MOCK_VOCAB_ITEMS: WordTestItem[] = [
  { id: 1, word: 'Ubiquitous', korMeaning: '어디에나 있는', engMeaning: 'present everywhere' },
  { id: 2, word: 'Ephemeral', korMeaning: '수명이 짧은', engMeaning: 'lasting for a short time' },
  {
    id: 3,
    word: 'persuade',
    korMeaning: '설득하다, 납득시키다',
    engMeaning:
      'to cause someone to agree or do something through reasoning or encouragement. to cause someone to agree or do something through reasoning or encouragement.',
  },
  {
    id: 4,
    word: 'Lugubrious',
    korMeaning: '침울한',
    engMeaning: 'looking or sounding sad and dismal',
  },
  {
    id: 5,
    word: 'Reticent',
    korMeaning: '과묵한',
    engMeaning: 'not revealing thoughts or feelings readily',
  },
  {
    id: 6,
    word: 'Loquacious',
    korMeaning: '수다스러운',
    engMeaning: 'tending to talk a great deal',
  },
  { id: 7, word: 'Pernicious', korMeaning: '해로운', engMeaning: 'having a harmful effect' },
  {
    id: 8,
    word: 'Sanguine',
    korMeaning: '낙관적인',
    engMeaning: 'optimistic, especially in a difficult situation',
  },
  {
    id: 9,
    word: 'Assiduous',
    korMeaning: '근면한',
    engMeaning: 'showing great care and perseverance',
  },
  { id: 10, word: 'Fastidious', korMeaning: '까다로운', engMeaning: 'very attentive to detail' },
  {
    id: 11,
    word: 'Obfuscate',
    korMeaning: '모호하게 하다',
    engMeaning: 'to make unclear or confusing',
  },
  {
    id: 12,
    word: 'Capricious',
    korMeaning: '변덕스러운',
    engMeaning: 'given to sudden changes of mood',
  },
  {
    id: 13,
    word: 'Esoteric',
    korMeaning: '난해한',
    engMeaning: 'intended for a small, specialized group',
  },
  {
    id: 14,
    word: 'Pedantic',
    korMeaning: '현학적인',
    engMeaning: 'overly concerned with minor details',
  },
  {
    id: 15,
    word: 'Ostentatious',
    korMeaning: '과시적인',
    engMeaning: 'characterized by vulgar display',
  },
  {
    id: 16,
    word: 'Pragmatic',
    korMeaning: '실용적인',
    engMeaning: 'dealing with things sensibly and realistically',
  },
  {
    id: 17,
    word: 'Iconoclast',
    korMeaning: '인습 타파주의자',
    engMeaning: 'a person who attacks cherished beliefs',
  },
  {
    id: 18,
    word: 'Cacophony',
    korMeaning: '불협화음',
    engMeaning: 'a harsh, discordant mixture of sounds',
  },
  {
    id: 19,
    word: 'Enervate',
    korMeaning: '기력을 빼앗다',
    engMeaning: 'to weaken physically or mentally',
  },
  { id: 20, word: 'Alacrity', korMeaning: '민첩함', engMeaning: 'brisk and cheerful readiness' },
  { id: 21, word: 'Perfidious', korMeaning: '불성실한', engMeaning: 'deceitful and untrustworthy' },
  {
    id: 22,
    word: 'Mellifluous',
    korMeaning: '감미로운',
    engMeaning: 'sweet or musical; pleasant to hear',
  },
  {
    id: 23,
    word: 'Vociferous',
    korMeaning: '소리 높여 외치는',
    engMeaning: 'expressing opinions loudly and forcefully',
  },
  {
    id: 24,
    word: 'Perspicacious',
    korMeaning: '통찰력 있는',
    engMeaning: 'having a ready insight; shrewd',
  },
  {
    id: 25,
    word: 'Recalcitrant',
    korMeaning: '반항적인',
    engMeaning: 'having an obstinately uncooperative attitude',
  },
  {
    id: 26,
    word: 'Truculent',
    korMeaning: '호전적인',
    engMeaning: 'eager or quick to argue or fight',
  },
  {
    id: 27,
    word: 'Magnanimous',
    korMeaning: '관대한',
    engMeaning: 'generous or forgiving, especially to rivals',
  },
  {
    id: 28,
    word: 'Quixotic',
    korMeaning: '비현실적인',
    engMeaning: 'exceedingly idealistic; unrealistic',
  },
  {
    id: 29,
    word: 'Tenacious',
    korMeaning: '끈질긴',
    engMeaning: 'tending to keep a firm hold; persistent',
  },
  { id: 30, word: 'Nefarious', korMeaning: '극악한', engMeaning: 'wicked or criminal' },
  {
    id: 31,
    word: 'Inimical',
    korMeaning: '적대적인',
    engMeaning: 'tending to obstruct or harm; hostile',
  },
  {
    id: 32,
    word: 'Querulous',
    korMeaning: '불평이 많은',
    engMeaning: 'complaining in a petulant way',
  },
  {
    id: 33,
    word: 'Pugnacious',
    korMeaning: '싸움을 좋아하는',
    engMeaning: 'eager or quick to argue or fight',
  },
  {
    id: 34,
    word: 'Volatile',
    korMeaning: '변동이 심한',
    engMeaning: 'liable to change rapidly and unpredictably',
  },
  {
    id: 35,
    word: 'Mendacious',
    korMeaning: '거짓말하는',
    engMeaning: 'not telling the truth; lying',
  },
  {
    id: 36,
    word: 'Inveterate',
    korMeaning: '뿌리 깊은',
    engMeaning: 'having a habit too firmly established to change',
  },
  { id: 37, word: 'Trepidation', korMeaning: '두려움', engMeaning: 'a feeling of fear or anxiety' },
  {
    id: 38,
    word: 'Obsequious',
    korMeaning: '아부하는',
    engMeaning: 'obedient or attentive to an excessive degree',
  },
  {
    id: 39,
    word: 'Circumspect',
    korMeaning: '신중한',
    engMeaning: 'wary and unwilling to take risks',
  },
  { id: 40, word: 'Discordant', korMeaning: '불화하는', engMeaning: 'disagreeing or incongruous' },
  { id: 41, word: 'Insolent', korMeaning: '무례한', engMeaning: 'showing a rude lack of respect' },
  {
    id: 42,
    word: 'Vivacious',
    korMeaning: '활기찬',
    engMeaning: 'attractively lively and animated',
  },
  {
    id: 43,
    word: 'Desolate',
    korMeaning: '황량한',
    engMeaning: 'feeling or showing misery or loneliness',
  },
  {
    id: 44,
    word: 'Ambivalent',
    korMeaning: '양가감정의',
    engMeaning: 'having mixed feelings about something',
  },
  { id: 45, word: 'Belligerent', korMeaning: '호전적인', engMeaning: 'hostile and aggressive' },
  { id: 46, word: 'Candid', korMeaning: '솔직한', engMeaning: 'truthful and straightforward' },
  {
    id: 47,
    word: 'Dogmatic',
    korMeaning: '독단적인',
    engMeaning: 'inclined to lay down principles as undeniably true',
  },
  {
    id: 48,
    word: 'Enigmatic',
    korMeaning: '수수께끼 같은',
    engMeaning: 'difficult to interpret or understand',
  },
  {
    id: 49,
    word: 'Garrulous',
    korMeaning: '수다스러운',
    engMeaning: 'excessively talkative, especially on trivial matters',
  },
  { id: 50, word: 'Laconic', korMeaning: '간결한', engMeaning: 'using very few words' },
];

// answer key — synonym은 정답 확인용이라 WordTestAnswer에 그대로 유지
export const MOCK_ANSWERS_WTM: Record<number, WordTestAnswer> = {
  1: { answer: '어디에나 있는', synonym: 'omnipresent' },
  2: { answer: '수명이 짧은', synonym: 'transient' },
  3: { answer: '설득하다, 납득시키다', synonym: 'convince' },
  4: { answer: '침울한', synonym: 'mournful' },
  5: { answer: '과묵한', synonym: 'reserved' },
  6: { answer: '수다스러운', synonym: 'talkative' },
  7: { answer: '해로운', synonym: 'detrimental' },
  8: { answer: '낙관적인', synonym: 'optimistic' },
  9: { answer: '근면한', synonym: 'diligent' },
  10: { answer: '까다로운', synonym: 'meticulous' },
  11: { answer: '모호하게 하다', synonym: 'obscure' },
  12: { answer: '변덕스러운', synonym: 'fickle' },
  13: { answer: '난해한', synonym: 'arcane' },
  14: { answer: '현학적인', synonym: 'nitpicky' },
  15: { answer: '과시적인', synonym: 'showy' },
  16: { answer: '실용적인', synonym: 'practical' },
  17: { answer: '인습 타파주의자', synonym: 'rebel' },
  18: { answer: '불협화음', synonym: 'discord' },
  19: { answer: '기력을 빼앗다', synonym: 'debilitate' },
  20: { answer: '민첩함', synonym: 'eagerness' },
  21: { answer: '불성실한', synonym: 'treacherous' },
  22: { answer: '감미로운', synonym: 'honeyed' },
  23: { answer: '소리 높여 외치는', synonym: 'clamorous' },
  24: { answer: '통찰력 있는', synonym: 'shrewd' },
  25: { answer: '반항적인', synonym: 'defiant' },
  26: { answer: '호전적인', synonym: 'aggressive' },
  27: { answer: '관대한', synonym: 'generous' },
  28: { answer: '비현실적인', synonym: 'idealistic' },
  29: { answer: '끈질긴', synonym: 'persistent' },
  30: { answer: '극악한', synonym: 'wicked' },
  31: { answer: '적대적인', synonym: 'hostile' },
  32: { answer: '불평이 많은', synonym: 'complaining' },
  33: { answer: '싸움을 좋아하는', synonym: 'belligerent' },
  34: { answer: '변동이 심한', synonym: 'unstable' },
  35: { answer: '거짓말하는', synonym: 'dishonest' },
  36: { answer: '뿌리 깊은', synonym: 'habitual' },
  37: { answer: '두려움', synonym: 'anxiety' },
  38: { answer: '아부하는', synonym: 'sycophantic' },
  39: { answer: '신중한', synonym: 'cautious' },
  40: { answer: '불화하는', synonym: 'conflicting' },
  41: { answer: '무례한', synonym: 'impudent' },
  42: { answer: '활기찬', synonym: 'lively' },
  43: { answer: '황량한', synonym: 'barren' },
  44: { answer: '양가감정의', synonym: 'conflicted' },
  45: { answer: '호전적인', synonym: 'aggressive' },
  46: { answer: '솔직한', synonym: 'frank' },
  47: { answer: '독단적인', synonym: 'doctrinaire' },
  48: { answer: '수수께끼 같은', synonym: 'mysterious' },
  49: { answer: '수다스러운', synonym: 'chatty' },
  50: { answer: '간결한', synonym: 'brief' },
};

export const MOCK_ANSWERS_MTW: Record<number, WordTestAnswer> = {
  1: { answer: 'Ubiquitous', synonym: 'omnipresent' },
  2: { answer: 'Ephemeral', synonym: 'transient' },
  3: { answer: 'persuade', synonym: 'convince' },
  4: { answer: 'Lugubrious', synonym: 'mournful' },
  5: { answer: 'Reticent', synonym: 'reserved' },
  6: { answer: 'Loquacious', synonym: 'talkative' },
  7: { answer: 'Pernicious', synonym: 'detrimental' },
  8: { answer: 'Sanguine', synonym: 'optimistic' },
  9: { answer: 'Assiduous', synonym: 'diligent' },
  10: { answer: 'Fastidious', synonym: 'meticulous' },
  11: { answer: 'Obfuscate', synonym: 'obscure' },
  12: { answer: 'Capricious', synonym: 'fickle' },
  13: { answer: 'Esoteric', synonym: 'arcane' },
  14: { answer: 'Pedantic', synonym: 'nitpicky' },
  15: { answer: 'Ostentatious', synonym: 'showy' },
  16: { answer: 'Pragmatic', synonym: 'practical' },
  17: { answer: 'Iconoclast', synonym: 'rebel' },
  18: { answer: 'Cacophony', synonym: 'discord' },
  19: { answer: 'Enervate', synonym: 'debilitate' },
  20: { answer: 'Alacrity', synonym: 'eagerness' },
  21: { answer: 'Perfidious', synonym: 'treacherous' },
  22: { answer: 'Mellifluous', synonym: 'honeyed' },
  23: { answer: 'Vociferous', synonym: 'clamorous' },
  24: { answer: 'Perspicacious', synonym: 'shrewd' },
  25: { answer: 'Recalcitrant', synonym: 'defiant' },
  26: { answer: 'Truculent', synonym: 'aggressive' },
  27: { answer: 'Magnanimous', synonym: 'generous' },
  28: { answer: 'Quixotic', synonym: 'idealistic' },
  29: { answer: 'Tenacious', synonym: 'persistent' },
  30: { answer: 'Nefarious', synonym: 'wicked' },
  31: { answer: 'Inimical', synonym: 'hostile' },
  32: { answer: 'Querulous', synonym: 'complaining' },
  33: { answer: 'Pugnacious', synonym: 'belligerent' },
  34: { answer: 'Volatile', synonym: 'unstable' },
  35: { answer: 'Mendacious', synonym: 'dishonest' },
  36: { answer: 'Inveterate', synonym: 'habitual' },
  37: { answer: 'Trepidation', synonym: 'anxiety' },
  38: { answer: 'Obsequious', synonym: 'sycophantic' },
  39: { answer: 'Circumspect', synonym: 'cautious' },
  40: { answer: 'Discordant', synonym: 'conflicting' },
  41: { answer: 'Insolent', synonym: 'impudent' },
  42: { answer: 'Vivacious', synonym: 'lively' },
  43: { answer: 'Desolate', synonym: 'barren' },
  44: { answer: 'Ambivalent', synonym: 'conflicted' },
  45: { answer: 'Belligerent', synonym: 'aggressive' },
  46: { answer: 'Candid', synonym: 'frank' },
  47: { answer: 'Dogmatic', synonym: 'doctrinaire' },
  48: { answer: 'Enigmatic', synonym: 'mysterious' },
  49: { answer: 'Garrulous', synonym: 'chatty' },
  50: { answer: 'Laconic', synonym: 'brief' },
};

export const MOCK_VOCAB_LIST: WordTestItem[] = [
  {
    id: 1,
    word: 'abandon',
    korMeaning: '포기하다',
    engMeaning: 'to cause someone to agree or do something through reasoning or encouragement.',
  },
  {
    id: 2,
    word: 'abolish',
    korMeaning: '주점, 막대, 법원, 막다, 금하다',
    engMeaning:
      'a long piece of material or place serving drinks / to block someone from entering or doing something',
  },
  { id: 3, word: 'abundant', korMeaning: '풍부한', engMeaning: 'existing in large quantities' },
  { id: 4, word: 'accelerate', korMeaning: '가속하다', engMeaning: 'to increase in speed' },
  { id: 5, word: 'accurate', korMeaning: '정확한', engMeaning: 'free from errors' },
  { id: 6, word: 'acknowledge', korMeaning: '인정하다', engMeaning: 'to accept or admit' },
  { id: 7, word: 'acquire', korMeaning: '습득하다', engMeaning: 'to obtain something' },
  { id: 8, word: 'adapt', korMeaning: '적응하다', engMeaning: 'to adjust to new conditions' },
  { id: 9, word: 'adequate', korMeaning: '충분한', engMeaning: 'satisfactory or acceptable' },
  { id: 10, word: 'advocate', korMeaning: '지지하다', engMeaning: 'to publicly support' },
  { id: 11, word: 'allocate', korMeaning: '할당하다', engMeaning: 'to distribute for a purpose' },
  { id: 12, word: 'alter', korMeaning: '변경하다', engMeaning: 'to change or modify' },
  { id: 13, word: 'ambiguous', korMeaning: '모호한', engMeaning: 'open to more than one meaning' },
  { id: 14, word: 'amplify', korMeaning: '증폭하다', engMeaning: 'to make larger or stronger' },
  { id: 15, word: 'analyze', korMeaning: '분석하다', engMeaning: 'to examine in detail' },
  { id: 16, word: 'anticipate', korMeaning: '예상하다', engMeaning: 'to expect or predict' },
  { id: 17, word: 'apparent', korMeaning: '명백한', engMeaning: 'clearly visible or understood' },
  { id: 18, word: 'appreciate', korMeaning: '감사하다', engMeaning: 'to recognize the value of' },
  { id: 19, word: 'approach', korMeaning: '접근하다', engMeaning: 'to come near or deal with' },
  { id: 20, word: 'appropriate', korMeaning: '적절한', engMeaning: 'suitable for a purpose' },
  { id: 21, word: 'approximately', korMeaning: '대략', engMeaning: 'close to but not exact' },
  { id: 22, word: 'arbitrary', korMeaning: '임의적인', engMeaning: 'based on random choice' },
  { id: 23, word: 'assert', korMeaning: '주장하다', engMeaning: 'to state a fact confidently' },
  { id: 24, word: 'assess', korMeaning: '평가하다', engMeaning: 'to evaluate or estimate' },
  { id: 25, word: 'assume', korMeaning: '가정하다', engMeaning: 'to suppose without proof' },
  { id: 26, word: 'attain', korMeaning: '달성하다', engMeaning: 'to succeed in achieving' },
  {
    id: 27,
    word: 'attribute',
    korMeaning: '~의 덕분으로 보다',
    engMeaning: 'to regard as caused by',
  },
  { id: 28, word: 'benefit', korMeaning: '이익', engMeaning: 'an advantage or profit' },
  { id: 29, word: 'capable', korMeaning: '유능한', engMeaning: 'having the ability to do' },
  { id: 30, word: 'cease', korMeaning: '중단하다', engMeaning: 'to come or bring to an end' },
  { id: 31, word: 'challenge', korMeaning: '도전하다', engMeaning: 'to dispute or test' },
  { id: 32, word: 'clarify', korMeaning: '명확히 하다', engMeaning: 'to make something clearer' },
  {
    id: 33,
    word: 'collaborate',
    korMeaning: '협력하다',
    engMeaning: 'to work jointly with others',
  },
  {
    id: 34,
    word: 'compensate',
    korMeaning: '보상하다',
    engMeaning: 'to give something to make up for loss',
  },
  { id: 35, word: 'complex', korMeaning: '복잡한', engMeaning: 'consisting of many parts' },
  { id: 36, word: 'comprehend', korMeaning: '이해하다', engMeaning: 'to understand fully' },
  { id: 37, word: 'concentrate', korMeaning: '집중하다', engMeaning: 'to focus attention on' },
  { id: 38, word: 'confirm', korMeaning: '확인하다', engMeaning: 'to establish the truth of' },
  { id: 39, word: 'consequence', korMeaning: '결과', engMeaning: 'a result of an action' },
  { id: 40, word: 'contribute', korMeaning: '기여하다', engMeaning: 'to give in order to help' },
  { id: 41, word: 'controversy', korMeaning: '논란', engMeaning: 'prolonged public disagreement' },
  { id: 42, word: 'convert', korMeaning: '전환하다', engMeaning: 'to change in form or character' },
  { id: 43, word: 'convince', korMeaning: '설득하다', engMeaning: 'to cause to believe something' },
  {
    id: 44,
    word: 'cooperate',
    korMeaning: '협동하다',
    engMeaning: 'to work together toward a goal',
  },
  { id: 45, word: 'decline', korMeaning: '감소하다', engMeaning: 'to become smaller or weaker' },
  { id: 46, word: 'define', korMeaning: '정의하다', engMeaning: 'to state the meaning of' },
  { id: 47, word: 'demonstrate', korMeaning: '증명하다', engMeaning: 'to show or prove clearly' },
  { id: 48, word: 'depict', korMeaning: '묘사하다', engMeaning: 'to represent in a picture' },
  { id: 49, word: 'derive', korMeaning: '유래하다', engMeaning: 'to obtain from a source' },
  { id: 50, word: 'determine', korMeaning: '결정하다', engMeaning: 'to cause something to occur' },
];

export const MOCK_VOCAB_REVIEW_ITEMS: VocabReviewItem[] = MOCK_VOCAB_ITEMS.map((item) => ({
  ...item,
  synonymAnswer: MOCK_ANSWERS_WTM[item.id]?.synonym ?? '',
}));
