export {
  MOCK_VOCAB_LIST,
  MOCK_VOCAB_ITEMS,
  MOCK_VOCAB_REVIEW_ITEMS,
  MOCK_ANSWERS_WTM,
  MOCK_ANSWERS_MTW,
} from './mockVocab';
export {
  MOCK_SENTENCE_ITEMS,
  MOCK_SENTENCE_ANSWERS,
  MOCK_ES_ROWS,
  MOCK_ES_TEMPLATE,
} from './mockSentence';

export const ITEMS_PER_PAGE = 10;
