import type { TestWord } from '@/entities/word';
import type { TestWordAnswer } from '../model/types';

export const MOCK_VOCAB_ITEMS: TestWord[] = [
  {
    id: 1,
    word: 'Ubiquitous',
    korMeaning: '어디에나 있는',
    engMeaning: 'present everywhere',
    synonym: 'omnipresent, omnipresent, omnipresent',
  },
  {
    id: 2,
    word: 'Ephemeral',
    korMeaning: '수명이 짧은',
    engMeaning: 'lasting for a short time',
    synonym: 'transient',
  },
  {
    id: 3,
    word: 'persuade',
    korMeaning: '설득하다, 납득시키다',
    engMeaning:
      'to cause someone to agree or do something through reasoning or encouragement. to cause someone to agree or do something through reasoning or encouragement.',
    synonym: 'convince',
  },
  {
    id: 4,
    word: 'Lugubrious',
    korMeaning: '침울한',
    engMeaning: 'looking or sounding sad and dismal',
    synonym: 'mournful',
  },
  {
    id: 5,
    word: 'Reticent',
    korMeaning: '과묵한',
    engMeaning: 'not revealing thoughts or feelings readily',
    synonym: 'reserved',
  },
  {
    id: 6,
    word: 'Loquacious',
    korMeaning: '수다스러운',
    engMeaning: 'tending to talk a great deal',
    synonym: 'talkative',
  },
  {
    id: 7,
    word: 'Pernicious',
    korMeaning: '해로운',
    engMeaning: 'having a harmful effect',
    synonym: 'detrimental',
  },
  {
    id: 8,
    word: 'Sanguine',
    korMeaning: '낙관적인',
    engMeaning: 'optimistic, especially in a difficult situation',
    synonym: 'optimistic',
  },
  {
    id: 9,
    word: 'Assiduous',
    korMeaning: '근면한',
    engMeaning: 'showing great care and perseverance',
    synonym: 'diligent',
  },
  {
    id: 10,
    word: 'Fastidious',
    korMeaning: '까다로운',
    engMeaning: 'very attentive to detail',
    synonym: 'meticulous',
  },
  {
    id: 11,
    word: 'Obfuscate',
    korMeaning: '모호하게 하다',
    engMeaning: 'to make unclear or confusing',
    synonym: 'obscure',
  },
  {
    id: 12,
    word: 'Capricious',
    korMeaning: '변덕스러운',
    engMeaning: 'given to sudden changes of mood',
    synonym: 'fickle',
  },
  {
    id: 13,
    word: 'Esoteric',
    korMeaning: '난해한',
    engMeaning: 'intended for a small, specialized group',
    synonym: 'arcane',
  },
  {
    id: 14,
    word: 'Pedantic',
    korMeaning: '현학적인',
    engMeaning: 'overly concerned with minor details',
    synonym: 'nitpicky',
  },
  {
    id: 15,
    word: 'Ostentatious',
    korMeaning: '과시적인',
    engMeaning: 'characterized by vulgar display',
    synonym: 'showy',
  },
  {
    id: 16,
    word: 'Pragmatic',
    korMeaning: '실용적인',
    engMeaning: 'dealing with things sensibly and realistically',
    synonym: 'practical',
  },
  {
    id: 17,
    word: 'Iconoclast',
    korMeaning: '인습 타파주의자',
    engMeaning: 'a person who attacks cherished beliefs',
    synonym: 'rebel',
  },
  {
    id: 18,
    word: 'Cacophony',
    korMeaning: '불협화음',
    engMeaning: 'a harsh, discordant mixture of sounds',
    synonym: 'discord',
  },
  {
    id: 19,
    word: 'Enervate',
    korMeaning: '기력을 빼앗다',
    engMeaning: 'to weaken physically or mentally',
    synonym: 'debilitate',
  },
  {
    id: 20,
    word: 'Alacrity',
    korMeaning: '민첩함',
    engMeaning: 'brisk and cheerful readiness',
    synonym: 'eagerness',
  },
  {
    id: 21,
    word: 'Perfidious',
    korMeaning: '불성실한',
    engMeaning: 'deceitful and untrustworthy',
    synonym: 'treacherous',
  },
  {
    id: 22,
    word: 'Mellifluous',
    korMeaning: '감미로운',
    engMeaning: 'sweet or musical; pleasant to hear',
    synonym: 'honeyed',
  },
  {
    id: 23,
    word: 'Vociferous',
    korMeaning: '소리 높여 외치는',
    engMeaning: 'expressing opinions loudly and forcefully',
    synonym: 'clamorous',
  },
  {
    id: 24,
    word: 'Perspicacious',
    korMeaning: '통찰력 있는',
    engMeaning: 'having a ready insight; shrewd',
    synonym: 'shrewd',
  },
  {
    id: 25,
    word: 'Recalcitrant',
    korMeaning: '반항적인',
    engMeaning: 'having an obstinately uncooperative attitude',
    synonym: 'defiant',
  },
  {
    id: 26,
    word: 'Truculent',
    korMeaning: '호전적인',
    engMeaning: 'eager or quick to argue or fight',
    synonym: 'aggressive',
  },
  {
    id: 27,
    word: 'Magnanimous',
    korMeaning: '관대한',
    engMeaning: 'generous or forgiving, especially to rivals',
    synonym: 'generous',
  },
  {
    id: 28,
    word: 'Quixotic',
    korMeaning: '비현실적인',
    engMeaning: 'exceedingly idealistic; unrealistic',
    synonym: 'idealistic',
  },
  {
    id: 29,
    word: 'Tenacious',
    korMeaning: '끈질긴',
    engMeaning: 'tending to keep a firm hold; persistent',
    synonym: 'persistent',
  },
  {
    id: 30,
    word: 'Nefarious',
    korMeaning: '극악한',
    engMeaning: 'wicked or criminal',
    synonym: 'wicked',
  },
  {
    id: 31,
    word: 'Inimical',
    korMeaning: '적대적인',
    engMeaning: 'tending to obstruct or harm; hostile',
    synonym: 'hostile',
  },
  {
    id: 32,
    word: 'Querulous',
    korMeaning: '불평이 많은',
    engMeaning: 'complaining in a petulant way',
    synonym: 'complaining',
  },
  {
    id: 33,
    word: 'Pugnacious',
    korMeaning: '싸움을 좋아하는',
    engMeaning: 'eager or quick to argue or fight',
    synonym: 'belligerent',
  },
  {
    id: 34,
    word: 'Volatile',
    korMeaning: '변동이 심한',
    engMeaning: 'liable to change rapidly and unpredictably',
    synonym: 'unstable',
  },
  {
    id: 35,
    word: 'Mendacious',
    korMeaning: '거짓말하는',
    engMeaning: 'not telling the truth; lying',
    synonym: 'dishonest',
  },
  {
    id: 36,
    word: 'Inveterate',
    korMeaning: '뿌리 깊은',
    engMeaning: 'having a habit too firmly established to change',
    synonym: 'habitual',
  },
  {
    id: 37,
    word: 'Trepidation',
    korMeaning: '두려움',
    engMeaning: 'a feeling of fear or anxiety',
    synonym: 'anxiety',
  },
  {
    id: 38,
    word: 'Obsequious',
    korMeaning: '아부하는',
    engMeaning: 'obedient or attentive to an excessive degree',
    synonym: 'sycophantic',
  },
  {
    id: 39,
    word: 'Circumspect',
    korMeaning: '신중한',
    engMeaning: 'wary and unwilling to take risks',
    synonym: 'cautious',
  },
  {
    id: 40,
    word: 'Discordant',
    korMeaning: '불화하는',
    engMeaning: 'disagreeing or incongruous',
    synonym: 'conflicting',
  },
  {
    id: 41,
    word: 'Insolent',
    korMeaning: '무례한',
    engMeaning: 'showing a rude lack of respect',
    synonym: 'impudent',
  },
  {
    id: 42,
    word: 'Vivacious',
    korMeaning: '활기찬',
    engMeaning: 'attractively lively and animated',
    synonym: 'lively',
  },
  {
    id: 43,
    word: 'Desolate',
    korMeaning: '황량한',
    engMeaning: 'feeling or showing misery or loneliness',
    synonym: 'barren',
  },
  {
    id: 44,
    word: 'Ambivalent',
    korMeaning: '양가감정의',
    engMeaning: 'having mixed feelings about something',
    synonym: 'conflicted',
  },
  {
    id: 45,
    word: 'Belligerent',
    korMeaning: '호전적인',
    engMeaning: 'hostile and aggressive',
    synonym: 'aggressive',
  },
  {
    id: 46,
    word: 'Candid',
    korMeaning: '솔직한',
    engMeaning: 'truthful and straightforward',
    synonym: 'frank',
  },
  {
    id: 47,
    word: 'Dogmatic',
    korMeaning: '독단적인',
    engMeaning: 'inclined to lay down principles as undeniably true',
    synonym: 'doctrinaire',
  },
  {
    id: 48,
    word: 'Enigmatic',
    korMeaning: '수수께끼 같은',
    engMeaning: 'difficult to interpret or understand',
    synonym: 'mysterious',
  },
  {
    id: 49,
    word: 'Garrulous',
    korMeaning: '수다스러운',
    engMeaning: 'excessively talkative, especially on trivial matters',
    synonym: 'chatty',
  },
  {
    id: 50,
    word: 'Laconic',
    korMeaning: '간결한',
    engMeaning: 'using very few words',
    synonym: 'brief',
  },
];

export const MOCK_ANSWERS_WTM: Record<number, TestWordAnswer> = Object.fromEntries(
  MOCK_VOCAB_ITEMS.map((item) => [
    item.id,
    { meaning: item.korMeaning, synonym: item.synonym ?? '' },
  ]),
);

export const MOCK_ANSWERS_MTW: Record<number, TestWordAnswer> = Object.fromEntries(
  MOCK_VOCAB_ITEMS.map((item) => [
    item.id,
    { meaning: item.word, synonym: item.synonym ?? '' },
  ]),
);

export const MOCK_VOCAB_LIST: TestWord[] = [
  {
    id: 1,
    word: 'abandon',
    korMeaning: '포기하다',
    engMeaning: 'to cause someone to agree or do something through reasoning or encouragement.',
    synonym: 'forsake',
  },
  {
    id: 2,
    word: 'abolish',
    korMeaning: '주점, 막대, 법원, 막다, 금하다',
    engMeaning:
      'a long piece of material or place serving drinks / to block someone from entering or doing something',
    synonym: 'eliminate',
  },
  {
    id: 3,
    word: 'abundant',
    korMeaning: '풍부한',
    engMeaning: 'existing in large quantities',
    synonym: 'plentiful',
  },
  {
    id: 4,
    word: 'accelerate',
    korMeaning: '가속하다',
    engMeaning: 'to increase in speed',
    synonym: 'hasten',
  },
  {
    id: 5,
    word: 'accurate',
    korMeaning: '정확한',
    engMeaning: 'free from errors',
    synonym: 'precise',
  },
  {
    id: 6,
    word: 'acknowledge',
    korMeaning: '인정하다',
    engMeaning: 'to accept or admit',
    synonym: 'recognize',
  },
  {
    id: 7,
    word: 'acquire',
    korMeaning: '습득하다',
    engMeaning: 'to obtain something',
    synonym: 'obtain',
  },
  {
    id: 8,
    word: 'adapt',
    korMeaning: '적응하다',
    engMeaning: 'to adjust to new conditions',
    synonym: 'adjust',
  },
  {
    id: 9,
    word: 'adequate',
    korMeaning: '충분한',
    engMeaning: 'satisfactory or acceptable',
    synonym: 'sufficient',
  },
  {
    id: 10,
    word: 'advocate',
    korMeaning: '지지하다',
    engMeaning: 'to publicly support',
    synonym: 'support',
  },
  {
    id: 11,
    word: 'allocate',
    korMeaning: '할당하다',
    engMeaning: 'to distribute for a purpose',
    synonym: 'assign',
  },
  {
    id: 12,
    word: 'alter',
    korMeaning: '변경하다',
    engMeaning: 'to change or modify',
    synonym: 'modify',
  },
  {
    id: 13,
    word: 'ambiguous',
    korMeaning: '모호한',
    engMeaning: 'open to more than one meaning',
    synonym: 'vague',
  },
  {
    id: 14,
    word: 'amplify',
    korMeaning: '증폭하다',
    engMeaning: 'to make larger or stronger',
    synonym: 'intensify',
  },
  {
    id: 15,
    word: 'analyze',
    korMeaning: '분석하다',
    engMeaning: 'to examine in detail',
    synonym: 'examine',
  },
  {
    id: 16,
    word: 'anticipate',
    korMeaning: '예상하다',
    engMeaning: 'to expect or predict',
    synonym: 'expect',
  },
  {
    id: 17,
    word: 'apparent',
    korMeaning: '명백한',
    engMeaning: 'clearly visible or understood',
    synonym: 'obvious',
  },
  {
    id: 18,
    word: 'appreciate',
    korMeaning: '감사하다',
    engMeaning: 'to recognize the value of',
    synonym: 'value',
  },
  {
    id: 19,
    word: 'approach',
    korMeaning: '접근하다',
    engMeaning: 'to come near or deal with',
    synonym: 'method',
  },
  {
    id: 20,
    word: 'appropriate',
    korMeaning: '적절한',
    engMeaning: 'suitable for a purpose',
    synonym: 'suitable',
  },
  {
    id: 21,
    word: 'approximately',
    korMeaning: '대략',
    engMeaning: 'close to but not exact',
    synonym: 'roughly',
  },
  {
    id: 22,
    word: 'arbitrary',
    korMeaning: '임의적인',
    engMeaning: 'based on random choice',
    synonym: 'random',
  },
  {
    id: 23,
    word: 'assert',
    korMeaning: '주장하다',
    engMeaning: 'to state a fact confidently',
    synonym: 'claim',
  },
  {
    id: 24,
    word: 'assess',
    korMeaning: '평가하다',
    engMeaning: 'to evaluate or estimate',
    synonym: 'evaluate',
  },
  {
    id: 25,
    word: 'assume',
    korMeaning: '가정하다',
    engMeaning: 'to suppose without proof',
    synonym: 'presume',
  },
  {
    id: 26,
    word: 'attain',
    korMeaning: '달성하다',
    engMeaning: 'to succeed in achieving',
    synonym: 'achieve',
  },
  {
    id: 27,
    word: 'attribute',
    korMeaning: '~의 덕분으로 보다',
    engMeaning: 'to regard as caused by',
    synonym: 'ascribe',
  },
  {
    id: 28,
    word: 'benefit',
    korMeaning: '이익',
    engMeaning: 'an advantage or profit',
    synonym: 'advantage',
  },
  {
    id: 29,
    word: 'capable',
    korMeaning: '유능한',
    engMeaning: 'having the ability to do',
    synonym: 'competent',
  },
  {
    id: 30,
    word: 'cease',
    korMeaning: '중단하다',
    engMeaning: 'to come or bring to an end',
    synonym: 'stop',
  },
  {
    id: 31,
    word: 'challenge',
    korMeaning: '도전하다',
    engMeaning: 'to dispute or test',
    synonym: 'contest',
  },
  {
    id: 32,
    word: 'clarify',
    korMeaning: '명확히 하다',
    engMeaning: 'to make something clearer',
    synonym: 'explain',
  },
  {
    id: 33,
    word: 'collaborate',
    korMeaning: '협력하다',
    engMeaning: 'to work jointly with others',
    synonym: 'cooperate',
  },
  {
    id: 34,
    word: 'compensate',
    korMeaning: '보상하다',
    engMeaning: 'to give something to make up for loss',
    synonym: 'reimburse',
  },
  {
    id: 35,
    word: 'complex',
    korMeaning: '복잡한',
    engMeaning: 'consisting of many parts',
    synonym: 'complicated',
  },
  {
    id: 36,
    word: 'comprehend',
    korMeaning: '이해하다',
    engMeaning: 'to understand fully',
    synonym: 'understand',
  },
  {
    id: 37,
    word: 'concentrate',
    korMeaning: '집중하다',
    engMeaning: 'to focus attention on',
    synonym: 'focus',
  },
  {
    id: 38,
    word: 'confirm',
    korMeaning: '확인하다',
    engMeaning: 'to establish the truth of',
    synonym: 'verify',
  },
  {
    id: 39,
    word: 'consequence',
    korMeaning: '결과',
    engMeaning: 'a result of an action',
    synonym: 'outcome',
  },
  {
    id: 40,
    word: 'contribute',
    korMeaning: '기여하다',
    engMeaning: 'to give in order to help',
    synonym: 'donate',
  },
  {
    id: 41,
    word: 'controversy',
    korMeaning: '논란',
    engMeaning: 'prolonged public disagreement',
    synonym: 'dispute',
  },
  {
    id: 42,
    word: 'convert',
    korMeaning: '전환하다',
    engMeaning: 'to change in form or character',
    synonym: 'transform',
  },
  {
    id: 43,
    word: 'convince',
    korMeaning: '설득하다',
    engMeaning: 'to cause to believe something',
    synonym: 'persuade',
  },
  {
    id: 44,
    word: 'cooperate',
    korMeaning: '협동하다',
    engMeaning: 'to work together toward a goal',
    synonym: 'collaborate',
  },
  {
    id: 45,
    word: 'decline',
    korMeaning: '감소하다',
    engMeaning: 'to become smaller or weaker',
    synonym: 'decrease',
  },
  {
    id: 46,
    word: 'define',
    korMeaning: '정의하다',
    engMeaning: 'to state the meaning of',
    synonym: 'specify',
  },
  {
    id: 47,
    word: 'demonstrate',
    korMeaning: '증명하다',
    engMeaning: 'to show or prove clearly',
    synonym: 'prove',
  },
  {
    id: 48,
    word: 'depict',
    korMeaning: '묘사하다',
    engMeaning: 'to represent in a picture',
    synonym: 'portray',
  },
  {
    id: 49,
    word: 'derive',
    korMeaning: '유래하다',
    engMeaning: 'to obtain from a source',
    synonym: 'obtain',
  },
  {
    id: 50,
    word: 'determine',
    korMeaning: '결정하다',
    engMeaning: 'to cause something to occur',
    synonym: 'decide',
  },
];
