/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as TeacherRouteImport } from './../routes/teacher'
import { Route as StudentRouteImport } from './../routes/student'
import { Route as PendingRouteImport } from './../routes/pending'
import { Route as OnboardingRouteImport } from './../routes/onboarding'
import { Route as MRouteImport } from './../routes/m'
import { Route as IndexRouteImport } from './../routes/index'
import { Route as TeacherIndexRouteImport } from './../routes/teacher/index'
import { Route as StudentIndexRouteImport } from './../routes/student/index'
import { Route as MIndexRouteImport } from './../routes/m/index'
import { Route as TeacherVocabularyBankRouteImport } from './../routes/teacher/vocabulary-bank'
import { Route as TeacherStudentsRouteImport } from './../routes/teacher/students'
import { Route as TeacherGradingRouteImport } from './../routes/teacher/grading'
import { Route as TeacherClinicsRouteImport } from './../routes/teacher/clinics'
import { Route as TeacherAdminRouteImport } from './../routes/teacher/admin'
import { Route as StudentWordTestRouteImport } from './../routes/student/word-test_'
import { Route as StudentDashboardRouteImport } from './../routes/student/dashboard'
import { Route as OauthCallbackRouteImport } from './../routes/oauth/callback'
import { Route as MUnsupportedRouteImport } from './../routes/m/unsupported'
import { Route as MLibraryRouteImport } from './../routes/m/library'
import { Route as MAccountRouteImport } from './../routes/m/account'
import { Route as StudentReviewDeckIndexRouteImport } from './../routes/student/review-deck/index'
import { Route as StudentPersonalWordsIndexRouteImport } from './../routes/student/personal-words/index'
import { Route as StudentLevelTestIndexRouteImport } from './../routes/student/level-test/index'
import { Route as TeacherStudentsStudentIdRouteImport } from './../routes/teacher/students_.$studentId'
import { Route as StudentSelfTestStudySetIdRouteImport } from './../routes/student_.self-test.$studySetId'
import { Route as StudentPersonalSelfTestPersonalWordSetIdRouteImport } from './../routes/student_.personal-self-test.$personalWordSetId'
import { Route as StudentReviewDeckWordsRouteImport } from './../routes/student/review-deck/words'
import { Route as StudentPersonalWordsPersonalWordSetIdRouteImport } from './../routes/student/personal-words/$personalWordSetId'
import { Route as StudentDashboardPendingReviewsRouteImport } from './../routes/student/dashboard_/pending-reviews'
import { Route as MWordsReviewRouteImport } from './../routes/m/words/review'
import { Route as MWordsPersonalIndexRouteImport } from './../routes/m/words/personal/index'
import { Route as TeacherExamsExamIdReviewRouteImport } from './../routes/teacher_.exams.$examId.review'
import { Route as TeacherExamsExamIdPreviewRouteImport } from './../routes/teacher_.exams.$examId.preview'
import { Route as TeacherStudentsStudentIdPendingReviewsRouteImport } from './../routes/teacher/students_.$studentId_/pending-reviews'
import { Route as TeacherClinicsStudentsStudentIdRouteImport } from './../routes/teacher/clinics_.students.$studentId'
import { Route as StudentExamsExamIdTakeRouteImport } from './../routes/student_.exams.$examId.take'
import { Route as StudentExamsExamIdReviewRouteImport } from './../routes/student_.exams.$examId.review'
import { Route as StudentWordTestIdWordsRouteImport } from './../routes/student/word-test/$id/words'
import { Route as StudentReviewDeckStudySetIdWordsRouteImport } from './../routes/student/review-deck/$studySetId/words'
import { Route as StudentLevelTestStudySetIdWordsRouteImport } from './../routes/student/level-test/$studySetId/words'
import { Route as StudentDashboardAssignedWordsStudySetIdRouteImport } from './../routes/student/dashboard_/assigned-words/$studySetId'
import { Route as MWordsPersonalPersonalWordSetIdRouteImport } from './../routes/m/words/personal/$personalWordSetId'
import { Route as MWordsAssignedStudySetIdRouteImport } from './../routes/m/words/assigned/$studySetId'
import { Route as TeacherStudentsStudentIdAssignedWordsStudySetIdRouteImport } from './../routes/teacher/students_.$studentId_/assigned-words/$studySetId'
import { Route as TeacherClinicsStudentsStudentIdPersonalWordsPersonalWordSetIdRouteImport } from './../routes/teacher/clinics_.students.$studentId_/personal-words.$personalWordSetId'

const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingRoute = PendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MRoute = MRouteImport.update({
  id: '/m',
  path: '/m',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherIndexRoute = TeacherIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeacherRoute,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const MIndexRoute = MIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MRoute,
} as any)
const TeacherVocabularyBankRoute = TeacherVocabularyBankRouteImport.update({
  id: '/vocabulary-bank',
  path: '/vocabulary-bank',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherStudentsRoute = TeacherStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherGradingRoute = TeacherGradingRouteImport.update({
  id: '/grading',
  path: '/grading',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherClinicsRoute = TeacherClinicsRouteImport.update({
  id: '/clinics',
  path: '/clinics',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherAdminRoute = TeacherAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => TeacherRoute,
} as any)
const StudentWordTestRoute = StudentWordTestRouteImport.update({
  id: '/word-test_',
  path: '/word-test',
  getParentRoute: () => StudentRoute,
} as any)
const StudentDashboardRoute = StudentDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => StudentRoute,
} as any)
const OauthCallbackRoute = OauthCallbackRouteImport.update({
  id: '/oauth/callback',
  path: '/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const MUnsupportedRoute = MUnsupportedRouteImport.update({
  id: '/unsupported',
  path: '/unsupported',
  getParentRoute: () => MRoute,
} as any)
const MLibraryRoute = MLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => MRoute,
} as any)
const MAccountRoute = MAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => MRoute,
} as any)
const StudentReviewDeckIndexRoute = StudentReviewDeckIndexRouteImport.update({
  id: '/review-deck/',
  path: '/review-deck/',
  getParentRoute: () => StudentRoute,
} as any)
const StudentPersonalWordsIndexRoute =
  StudentPersonalWordsIndexRouteImport.update({
    id: '/personal-words/',
    path: '/personal-words/',
    getParentRoute: () => StudentRoute,
  } as any)
const StudentLevelTestIndexRoute = StudentLevelTestIndexRouteImport.update({
  id: '/level-test/',
  path: '/level-test/',
  getParentRoute: () => StudentRoute,
} as any)
const TeacherStudentsStudentIdRoute =
  TeacherStudentsStudentIdRouteImport.update({
    id: '/students_/$studentId',
    path: '/students/$studentId',
    getParentRoute: () => TeacherRoute,
  } as any)
const StudentSelfTestStudySetIdRoute =
  StudentSelfTestStudySetIdRouteImport.update({
    id: '/student_/self-test/$studySetId',
    path: '/student/self-test/$studySetId',
    getParentRoute: () => rootRouteImport,
  } as any)
const StudentPersonalSelfTestPersonalWordSetIdRoute =
  StudentPersonalSelfTestPersonalWordSetIdRouteImport.update({
    id: '/student_/personal-self-test/$personalWordSetId',
    path: '/student/personal-self-test/$personalWordSetId',
    getParentRoute: () => rootRouteImport,
  } as any)
const StudentReviewDeckWordsRoute = StudentReviewDeckWordsRouteImport.update({
  id: '/review-deck/words',
  path: '/review-deck/words',
  getParentRoute: () => StudentRoute,
} as any)
const StudentPersonalWordsPersonalWordSetIdRoute =
  StudentPersonalWordsPersonalWordSetIdRouteImport.update({
    id: '/personal-words/$personalWordSetId',
    path: '/personal-words/$personalWordSetId',
    getParentRoute: () => StudentRoute,
  } as any)
const StudentDashboardPendingReviewsRoute =
  StudentDashboardPendingReviewsRouteImport.update({
    id: '/dashboard_/pending-reviews',
    path: '/dashboard/pending-reviews',
    getParentRoute: () => StudentRoute,
  } as any)
const MWordsReviewRoute = MWordsReviewRouteImport.update({
  id: '/words/review',
  path: '/words/review',
  getParentRoute: () => MRoute,
} as any)
const MWordsPersonalIndexRoute = MWordsPersonalIndexRouteImport.update({
  id: '/words/personal/',
  path: '/words/personal/',
  getParentRoute: () => MRoute,
} as any)
const TeacherExamsExamIdReviewRoute =
  TeacherExamsExamIdReviewRouteImport.update({
    id: '/teacher_/exams/$examId/review',
    path: '/teacher/exams/$examId/review',
    getParentRoute: () => rootRouteImport,
  } as any)
const TeacherExamsExamIdPreviewRoute =
  TeacherExamsExamIdPreviewRouteImport.update({
    id: '/teacher_/exams/$examId/preview',
    path: '/teacher/exams/$examId/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const TeacherStudentsStudentIdPendingReviewsRoute =
  TeacherStudentsStudentIdPendingReviewsRouteImport.update({
    id: '/students_/$studentId_/pending-reviews',
    path: '/students/$studentId/pending-reviews',
    getParentRoute: () => TeacherRoute,
  } as any)
const TeacherClinicsStudentsStudentIdRoute =
  TeacherClinicsStudentsStudentIdRouteImport.update({
    id: '/clinics_/students/$studentId',
    path: '/clinics/students/$studentId',
    getParentRoute: () => TeacherRoute,
  } as any)
const StudentExamsExamIdTakeRoute = StudentExamsExamIdTakeRouteImport.update({
  id: '/student_/exams/$examId/take',
  path: '/student/exams/$examId/take',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentExamsExamIdReviewRoute =
  StudentExamsExamIdReviewRouteImport.update({
    id: '/student_/exams/$examId/review',
    path: '/student/exams/$examId/review',
    getParentRoute: () => rootRouteImport,
  } as any)
const StudentWordTestIdWordsRoute = StudentWordTestIdWordsRouteImport.update({
  id: '/word-test/$id/words',
  path: '/word-test/$id/words',
  getParentRoute: () => StudentRoute,
} as any)
const StudentReviewDeckStudySetIdWordsRoute =
  StudentReviewDeckStudySetIdWordsRouteImport.update({
    id: '/review-deck/$studySetId/words',
    path: '/review-deck/$studySetId/words',
    getParentRoute: () => StudentRoute,
  } as any)
const StudentLevelTestStudySetIdWordsRoute =
  StudentLevelTestStudySetIdWordsRouteImport.update({
    id: '/level-test/$studySetId/words',
    path: '/level-test/$studySetId/words',
    getParentRoute: () => StudentRoute,
  } as any)
const StudentDashboardAssignedWordsStudySetIdRoute =
  StudentDashboardAssignedWordsStudySetIdRouteImport.update({
    id: '/dashboard_/assigned-words/$studySetId',
    path: '/dashboard/assigned-words/$studySetId',
    getParentRoute: () => StudentRoute,
  } as any)
const MWordsPersonalPersonalWordSetIdRoute =
  MWordsPersonalPersonalWordSetIdRouteImport.update({
    id: '/words/personal/$personalWordSetId',
    path: '/words/personal/$personalWordSetId',
    getParentRoute: () => MRoute,
  } as any)
const MWordsAssignedStudySetIdRoute =
  MWordsAssignedStudySetIdRouteImport.update({
    id: '/words/assigned/$studySetId',
    path: '/words/assigned/$studySetId',
    getParentRoute: () => MRoute,
  } as any)
const TeacherStudentsStudentIdAssignedWordsStudySetIdRoute =
  TeacherStudentsStudentIdAssignedWordsStudySetIdRouteImport.update({
    id: '/students_/$studentId_/assigned-words/$studySetId',
    path: '/students/$studentId/assigned-words/$studySetId',
    getParentRoute: () => TeacherRoute,
  } as any)
const TeacherClinicsStudentsStudentIdPersonalWordsPersonalWordSetIdRoute =
  TeacherClinicsStudentsStudentIdPersonalWordsPersonalWordSetIdRouteImport.update(
    {
      id: '/clinics_/students/$studentId_/personal-words/$personalWordSetId',
      path: '/clinics/students/$studentId/personal-words/$personalWordSetId',
      getParentRoute: () => TeacherRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/m': typeof MRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/pending': typeof PendingRoute
  '/student': typeof StudentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/m/account': typeof MAccountRoute
  '/m/library': typeof MLibraryRoute
  '/m/unsupported': typeof MUnsupportedRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/word-test': typeof StudentWordTestRoute
  '/teacher/admin': typeof TeacherAdminRoute
  '/teacher/clinics': typeof TeacherClinicsRoute
  '/teacher/grading': typeof TeacherGradingRoute
  '/teacher/students': typeof TeacherStudentsRoute
  '/teacher/vocabulary-bank': typeof TeacherVocabularyBankRoute
  '/m/': typeof MIndexRoute
  '/student/': typeof StudentIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/m/words/review': typeof MWordsReviewRoute
  '/student/dashboard/pending-reviews': typeof StudentDashboardPendingReviewsRoute
  '/student/personal-words/$personalWordSetId': typeof StudentPersonalWordsPersonalWordSetIdRoute
  '/student/review-deck/words': typeof StudentReviewDeckWordsRoute
  '/student/personal-self-test/$personalWordSetId': typeof StudentPersonalSelfTestPersonalWordSetIdRoute
  '/student/self-test/$studySetId': typeof StudentSelfTestStudySetIdRoute
  '/teacher/students/$studentId': typeof TeacherStudentsStudentIdRoute
  '/student/level-test/': typeof StudentLevelTestIndexRoute
  '/student/personal-words/': typeof StudentPersonalWordsIndexRoute
  '/student/review-deck/': typeof StudentReviewDeckIndexRoute
  '/m/words/assigned/$studySetId': typeof MWordsAssignedStudySetIdRoute
  '/m/words/personal/$personalWordSetId': typeof MWordsPersonalPersonalWordSetIdRoute
  '/student/dashboard/assigned-words/$studySetId': typeof StudentDashboardAssignedWordsStudySetIdRoute
  '/student/level-test/$studySetId/words': typeof StudentLevelTestStudySetIdWordsRoute
  '/student/review-deck/$studySetId/words': typeof StudentReviewDeckStudySetIdWordsRoute
  '/student/word-test/$id/words': typeof StudentWordTestIdWordsRoute
  '/student/exams/$examId/review': typeof StudentExamsExamIdReviewRoute
  '/student/exams/$examId/take': typeof StudentExamsExamIdTakeRoute
  '/teacher/clinics/students/$studentId': typeof TeacherClinicsStudentsStudentIdRoute
  '/teacher/students/$studentId/pending-reviews': typeof TeacherStudentsStudentIdPendingReviewsRoute
  '/teacher/exams/$examId/preview': typeof TeacherExamsExamIdPreviewRoute
  '/teacher/exams/$examId/review': typeof TeacherExamsExamIdReviewRoute
  '/m/words/personal/': typeof MWordsPersonalIndexRoute
  '/teacher/students/$studentId/assigned-words/$studySetId': typeof TeacherStudentsStudentIdAssignedWordsStudySetIdRoute
  '/teacher/clinics/students/$studentId/personal-words/$personalWordSetId': typeof TeacherClinicsStudentsStudentIdPersonalWordsPersonalWordSetIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/pending': typeof PendingRoute
  '/m/account': typeof MAccountRoute
  '/m/library': typeof MLibraryRoute
  '/m/unsupported': typeof MUnsupportedRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/word-test': typeof StudentWordTestRoute
  '/teacher/admin': typeof TeacherAdminRoute
  '/teacher/clinics': typeof TeacherClinicsRoute
  '/teacher/grading': typeof TeacherGradingRoute
  '/teacher/students': typeof TeacherStudentsRoute
  '/teacher/vocabulary-bank': typeof TeacherVocabularyBankRoute
  '/m': typeof MIndexRoute
  '/student': typeof StudentIndexRoute
  '/teacher': typeof TeacherIndexRoute
  '/m/words/review': typeof MWordsReviewRoute
  '/student/dashboard/pending-reviews': typeof StudentDashboardPendingReviewsRoute
  '/student/personal-words/$personalWordSetId': typeof StudentPersonalWordsPersonalWordSetIdRoute
  '/student/review-deck/words': typeof StudentReviewDeckWordsRoute
  '/student/personal-self-test/$personalWordSetId': typeof StudentPersonalSelfTestPersonalWordSetIdRoute
  '/student/self-test/$studySetId': typeof StudentSelfTestStudySetIdRoute
  '/teacher/students/$studentId': typeof TeacherStudentsStudentIdRoute
  '/student/level-test': typeof StudentLevelTestIndexRoute
  '/student/personal-words': typeof StudentPersonalWordsIndexRoute
  '/student/review-deck': typeof StudentReviewDeckIndexRoute
  '/m/words/assigned/$studySetId': typeof MWordsAssignedStudySetIdRoute
  '/m/words/personal/$personalWordSetId': typeof MWordsPersonalPersonalWordSetIdRoute
  '/student/dashboard/assigned-words/$studySetId': typeof StudentDashboardAssignedWordsStudySetIdRoute
  '/student/level-test/$studySetId/words': typeof StudentLevelTestStudySetIdWordsRoute
  '/student/review-deck/$studySetId/words': typeof StudentReviewDeckStudySetIdWordsRoute
  '/student/word-test/$id/words': typeof StudentWordTestIdWordsRoute
  '/student/exams/$examId/review': typeof StudentExamsExamIdReviewRoute
  '/student/exams/$examId/take': typeof StudentExamsExamIdTakeRoute
  '/teacher/clinics/students/$studentId': typeof TeacherClinicsStudentsStudentIdRoute
  '/teacher/students/$studentId/pending-reviews': typeof TeacherStudentsStudentIdPendingReviewsRoute
  '/teacher/exams/$examId/preview': typeof TeacherExamsExamIdPreviewRoute
  '/teacher/exams/$examId/review': typeof TeacherExamsExamIdReviewRoute
  '/m/words/personal': typeof MWordsPersonalIndexRoute
  '/teacher/students/$studentId/assigned-words/$studySetId': typeof TeacherStudentsStudentIdAssignedWordsStudySetIdRoute
  '/teacher/clinics/students/$studentId/personal-words/$personalWordSetId': typeof TeacherClinicsStudentsStudentIdPersonalWordsPersonalWordSetIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/m': typeof MRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/pending': typeof PendingRoute
  '/student': typeof StudentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/m/account': typeof MAccountRoute
  '/m/library': typeof MLibraryRoute
  '/m/unsupported': typeof MUnsupportedRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/word-test_': typeof StudentWordTestRoute
  '/teacher/admin': typeof TeacherAdminRoute
  '/teacher/clinics': typeof TeacherClinicsRoute
  '/teacher/grading': typeof TeacherGradingRoute
  '/teacher/students': typeof TeacherStudentsRoute
  '/teacher/vocabulary-bank': typeof TeacherVocabularyBankRoute
  '/m/': typeof MIndexRoute
  '/student/': typeof StudentIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/m/words/review': typeof MWordsReviewRoute
  '/student/dashboard_/pending-reviews': typeof StudentDashboardPendingReviewsRoute
  '/student/personal-words/$personalWordSetId': typeof StudentPersonalWordsPersonalWordSetIdRoute
  '/student/review-deck/words': typeof StudentReviewDeckWordsRoute
  '/student_/personal-self-test/$personalWordSetId': typeof StudentPersonalSelfTestPersonalWordSetIdRoute
  '/student_/self-test/$studySetId': typeof StudentSelfTestStudySetIdRoute
  '/teacher/students_/$studentId': typeof TeacherStudentsStudentIdRoute
  '/student/level-test/': typeof StudentLevelTestIndexRoute
  '/student/personal-words/': typeof StudentPersonalWordsIndexRoute
  '/student/review-deck/': typeof StudentReviewDeckIndexRoute
  '/m/words/assigned/$studySetId': typeof MWordsAssignedStudySetIdRoute
  '/m/words/personal/$personalWordSetId': typeof MWordsPersonalPersonalWordSetIdRoute
  '/student/dashboard_/assigned-words/$studySetId': typeof StudentDashboardAssignedWordsStudySetIdRoute
  '/student/level-test/$studySetId/words': typeof StudentLevelTestStudySetIdWordsRoute
  '/student/review-deck/$studySetId/words': typeof StudentReviewDeckStudySetIdWordsRoute
  '/student/word-test/$id/words': typeof StudentWordTestIdWordsRoute
  '/student_/exams/$examId/review': typeof StudentExamsExamIdReviewRoute
  '/student_/exams/$examId/take': typeof StudentExamsExamIdTakeRoute
  '/teacher/clinics_/students/$studentId': typeof TeacherClinicsStudentsStudentIdRoute
  '/teacher/students_/$studentId_/pending-reviews': typeof TeacherStudentsStudentIdPendingReviewsRoute
  '/teacher_/exams/$examId/preview': typeof TeacherExamsExamIdPreviewRoute
  '/teacher_/exams/$examId/review': typeof TeacherExamsExamIdReviewRoute
  '/m/words/personal/': typeof MWordsPersonalIndexRoute
  '/teacher/students_/$studentId_/assigned-words/$studySetId': typeof TeacherStudentsStudentIdAssignedWordsStudySetIdRoute
  '/teacher/clinics_/students/$studentId_/personal-words/$personalWordSetId': typeof TeacherClinicsStudentsStudentIdPersonalWordsPersonalWordSetIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/m'
    | '/onboarding'
    | '/pending'
    | '/student'
    | '/teacher'
    | '/m/account'
    | '/m/library'
    | '/m/unsupported'
    | '/oauth/callback'
    | '/student/dashboard'
    | '/student/word-test'
    | '/teacher/admin'
    | '/teacher/clinics'
    | '/teacher/grading'
    | '/teacher/students'
    | '/teacher/vocabulary-bank'
    | '/m/'
    | '/student/'
    | '/teacher/'
    | '/m/words/review'
    | '/student/dashboard/pending-reviews'
    | '/student/personal-words/$personalWordSetId'
    | '/student/review-deck/words'
    | '/student/personal-self-test/$personalWordSetId'
    | '/student/self-test/$studySetId'
    | '/teacher/students/$studentId'
    | '/student/level-test/'
    | '/student/personal-words/'
    | '/student/review-deck/'
    | '/m/words/assigned/$studySetId'
    | '/m/words/personal/$personalWordSetId'
    | '/student/dashboard/assigned-words/$studySetId'
    | '/student/level-test/$studySetId/words'
    | '/student/review-deck/$studySetId/words'
    | '/student/word-test/$id/words'
    | '/student/exams/$examId/review'
    | '/student/exams/$examId/take'
    | '/teacher/clinics/students/$studentId'
    | '/teacher/students/$studentId/pending-reviews'
    | '/teacher/exams/$examId/preview'
    | '/teacher/exams/$examId/review'
    | '/m/words/personal/'
    | '/teacher/students/$studentId/assigned-words/$studySetId'
    | '/teacher/clinics/students/$studentId/personal-words/$personalWordSetId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/pending'
    | '/m/account'
    | '/m/library'
    | '/m/unsupported'
    | '/oauth/callback'
    | '/student/dashboard'
    | '/student/word-test'
    | '/teacher/admin'
    | '/teacher/clinics'
    | '/teacher/grading'
    | '/teacher/students'
    | '/teacher/vocabulary-bank'
    | '/m'
    | '/student'
    | '/teacher'
    | '/m/words/review'
    | '/student/dashboard/pending-reviews'
    | '/student/personal-words/$personalWordSetId'
    | '/student/review-deck/words'
    | '/student/personal-self-test/$personalWordSetId'
    | '/student/self-test/$studySetId'
    | '/teacher/students/$studentId'
    | '/student/level-test'
    | '/student/personal-words'
    | '/student/review-deck'
    | '/m/words/assigned/$studySetId'
    | '/m/words/personal/$personalWordSetId'
    | '/student/dashboard/assigned-words/$studySetId'
    | '/student/level-test/$studySetId/words'
    | '/student/review-deck/$studySetId/words'
    | '/student/word-test/$id/words'
    | '/student/exams/$examId/review'
    | '/student/exams/$examId/take'
    | '/teacher/clinics/students/$studentId'
    | '/teacher/students/$studentId/pending-reviews'
    | '/teacher/exams/$examId/preview'
    | '/teacher/exams/$examId/review'
    | '/m/words/personal'
    | '/teacher/students/$studentId/assigned-words/$studySetId'
    | '/teacher/clinics/students/$studentId/personal-words/$personalWordSetId'
  id:
    | '__root__'
    | '/'
    | '/m'
    | '/onboarding'
    | '/pending'
    | '/student'
    | '/teacher'
    | '/m/account'
    | '/m/library'
    | '/m/unsupported'
    | '/oauth/callback'
    | '/student/dashboard'
    | '/student/word-test_'
    | '/teacher/admin'
    | '/teacher/clinics'
    | '/teacher/grading'
    | '/teacher/students'
    | '/teacher/vocabulary-bank'
    | '/m/'
    | '/student/'
    | '/teacher/'
    | '/m/words/review'
    | '/student/dashboard_/pending-reviews'
    | '/student/personal-words/$personalWordSetId'
    | '/student/review-deck/words'
    | '/student_/personal-self-test/$personalWordSetId'
    | '/student_/self-test/$studySetId'
    | '/teacher/students_/$studentId'
    | '/student/level-test/'
    | '/student/personal-words/'
    | '/student/review-deck/'
    | '/m/words/assigned/$studySetId'
    | '/m/words/personal/$personalWordSetId'
    | '/student/dashboard_/assigned-words/$studySetId'
    | '/student/level-test/$studySetId/words'
    | '/student/review-deck/$studySetId/words'
    | '/student/word-test/$id/words'
    | '/student_/exams/$examId/review'
    | '/student_/exams/$examId/take'
    | '/teacher/clinics_/students/$studentId'
    | '/teacher/students_/$studentId_/pending-reviews'
    | '/teacher_/exams/$examId/preview'
    | '/teacher_/exams/$examId/review'
    | '/m/words/personal/'
    | '/teacher/students_/$studentId_/assigned-words/$studySetId'
    | '/teacher/clinics_/students/$studentId_/personal-words/$personalWordSetId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MRoute: typeof MRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  PendingRoute: typeof PendingRoute
  StudentRoute: typeof StudentRouteWithChildren
  TeacherRoute: typeof TeacherRouteWithChildren
  OauthCallbackRoute: typeof OauthCallbackRoute
  StudentPersonalSelfTestPersonalWordSetIdRoute: typeof StudentPersonalSelfTestPersonalWordSetIdRoute
  StudentSelfTestStudySetIdRoute: typeof StudentSelfTestStudySetIdRoute
  StudentExamsExamIdReviewRoute: typeof StudentExamsExamIdReviewRoute
  StudentExamsExamIdTakeRoute: typeof StudentExamsExamIdTakeRoute
  TeacherExamsExamIdPreviewRoute: typeof TeacherExamsExamIdPreviewRoute
  TeacherExamsExamIdReviewRoute: typeof TeacherExamsExamIdReviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending': {
      id: '/pending'
      path: '/pending'
      fullPath: '/pending'
      preLoaderRoute: typeof PendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m': {
      id: '/m'
      path: '/m'
      fullPath: '/m'
      preLoaderRoute: typeof MRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/': {
      id: '/teacher/'
      path: '/'
      fullPath: '/teacher/'
      preLoaderRoute: typeof TeacherIndexRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/m/': {
      id: '/m/'
      path: '/'
      fullPath: '/m/'
      preLoaderRoute: typeof MIndexRouteImport
      parentRoute: typeof MRoute
    }
    '/teacher/vocabulary-bank': {
      id: '/teacher/vocabulary-bank'
      path: '/vocabulary-bank'
      fullPath: '/teacher/vocabulary-bank'
      preLoaderRoute: typeof TeacherVocabularyBankRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/students': {
      id: '/teacher/students'
      path: '/students'
      fullPath: '/teacher/students'
      preLoaderRoute: typeof TeacherStudentsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/grading': {
      id: '/teacher/grading'
      path: '/grading'
      fullPath: '/teacher/grading'
      preLoaderRoute: typeof TeacherGradingRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/clinics': {
      id: '/teacher/clinics'
      path: '/clinics'
      fullPath: '/teacher/clinics'
      preLoaderRoute: typeof TeacherClinicsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/admin': {
      id: '/teacher/admin'
      path: '/admin'
      fullPath: '/teacher/admin'
      preLoaderRoute: typeof TeacherAdminRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/student/word-test_': {
      id: '/student/word-test_'
      path: '/word-test'
      fullPath: '/student/word-test'
      preLoaderRoute: typeof StudentWordTestRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/dashboard': {
      id: '/student/dashboard'
      path: '/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof StudentDashboardRouteImport
      parentRoute: typeof StudentRoute
    }
    '/oauth/callback': {
      id: '/oauth/callback'
      path: '/oauth/callback'
      fullPath: '/oauth/callback'
      preLoaderRoute: typeof OauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/unsupported': {
      id: '/m/unsupported'
      path: '/unsupported'
      fullPath: '/m/unsupported'
      preLoaderRoute: typeof MUnsupportedRouteImport
      parentRoute: typeof MRoute
    }
    '/m/library': {
      id: '/m/library'
      path: '/library'
      fullPath: '/m/library'
      preLoaderRoute: typeof MLibraryRouteImport
      parentRoute: typeof MRoute
    }
    '/m/account': {
      id: '/m/account'
      path: '/account'
      fullPath: '/m/account'
      preLoaderRoute: typeof MAccountRouteImport
      parentRoute: typeof MRoute
    }
    '/student/review-deck/': {
      id: '/student/review-deck/'
      path: '/review-deck'
      fullPath: '/student/review-deck/'
      preLoaderRoute: typeof StudentReviewDeckIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/personal-words/': {
      id: '/student/personal-words/'
      path: '/personal-words'
      fullPath: '/student/personal-words/'
      preLoaderRoute: typeof StudentPersonalWordsIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/level-test/': {
      id: '/student/level-test/'
      path: '/level-test'
      fullPath: '/student/level-test/'
      preLoaderRoute: typeof StudentLevelTestIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/teacher/students_/$studentId': {
      id: '/teacher/students_/$studentId'
      path: '/students/$studentId'
      fullPath: '/teacher/students/$studentId'
      preLoaderRoute: typeof TeacherStudentsStudentIdRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/student_/self-test/$studySetId': {
      id: '/student_/self-test/$studySetId'
      path: '/student/self-test/$studySetId'
      fullPath: '/student/self-test/$studySetId'
      preLoaderRoute: typeof StudentSelfTestStudySetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student_/personal-self-test/$personalWordSetId': {
      id: '/student_/personal-self-test/$personalWordSetId'
      path: '/student/personal-self-test/$personalWordSetId'
      fullPath: '/student/personal-self-test/$personalWordSetId'
      preLoaderRoute: typeof StudentPersonalSelfTestPersonalWordSetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/review-deck/words': {
      id: '/student/review-deck/words'
      path: '/review-deck/words'
      fullPath: '/student/review-deck/words'
      preLoaderRoute: typeof StudentReviewDeckWordsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/personal-words/$personalWordSetId': {
      id: '/student/personal-words/$personalWordSetId'
      path: '/personal-words/$personalWordSetId'
      fullPath: '/student/personal-words/$personalWordSetId'
      preLoaderRoute: typeof StudentPersonalWordsPersonalWordSetIdRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/dashboard_/pending-reviews': {
      id: '/student/dashboard_/pending-reviews'
      path: '/dashboard/pending-reviews'
      fullPath: '/student/dashboard/pending-reviews'
      preLoaderRoute: typeof StudentDashboardPendingReviewsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/m/words/review': {
      id: '/m/words/review'
      path: '/words/review'
      fullPath: '/m/words/review'
      preLoaderRoute: typeof MWordsReviewRouteImport
      parentRoute: typeof MRoute
    }
    '/m/words/personal/': {
      id: '/m/words/personal/'
      path: '/words/personal'
      fullPath: '/m/words/personal/'
      preLoaderRoute: typeof MWordsPersonalIndexRouteImport
      parentRoute: typeof MRoute
    }
    '/teacher_/exams/$examId/review': {
      id: '/teacher_/exams/$examId/review'
      path: '/teacher/exams/$examId/review'
      fullPath: '/teacher/exams/$examId/review'
      preLoaderRoute: typeof TeacherExamsExamIdReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher_/exams/$examId/preview': {
      id: '/teacher_/exams/$examId/preview'
      path: '/teacher/exams/$examId/preview'
      fullPath: '/teacher/exams/$examId/preview'
      preLoaderRoute: typeof TeacherExamsExamIdPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/students_/$studentId_/pending-reviews': {
      id: '/teacher/students_/$studentId_/pending-reviews'
      path: '/students/$studentId/pending-reviews'
      fullPath: '/teacher/students/$studentId/pending-reviews'
      preLoaderRoute: typeof TeacherStudentsStudentIdPendingReviewsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/clinics_/students/$studentId': {
      id: '/teacher/clinics_/students/$studentId'
      path: '/clinics/students/$studentId'
      fullPath: '/teacher/clinics/students/$studentId'
      preLoaderRoute: typeof TeacherClinicsStudentsStudentIdRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/student_/exams/$examId/take': {
      id: '/student_/exams/$examId/take'
      path: '/student/exams/$examId/take'
      fullPath: '/student/exams/$examId/take'
      preLoaderRoute: typeof StudentExamsExamIdTakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student_/exams/$examId/review': {
      id: '/student_/exams/$examId/review'
      path: '/student/exams/$examId/review'
      fullPath: '/student/exams/$examId/review'
      preLoaderRoute: typeof StudentExamsExamIdReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/word-test/$id/words': {
      id: '/student/word-test/$id/words'
      path: '/word-test/$id/words'
      fullPath: '/student/word-test/$id/words'
      preLoaderRoute: typeof StudentWordTestIdWordsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/review-deck/$studySetId/words': {
      id: '/student/review-deck/$studySetId/words'
      path: '/review-deck/$studySetId/words'
      fullPath: '/student/review-deck/$studySetId/words'
      preLoaderRoute: typeof StudentReviewDeckStudySetIdWordsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/level-test/$studySetId/words': {
      id: '/student/level-test/$studySetId/words'
      path: '/level-test/$studySetId/words'
      fullPath: '/student/level-test/$studySetId/words'
      preLoaderRoute: typeof StudentLevelTestStudySetIdWordsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/dashboard_/assigned-words/$studySetId': {
      id: '/student/dashboard_/assigned-words/$studySetId'
      path: '/dashboard/assigned-words/$studySetId'
      fullPath: '/student/dashboard/assigned-words/$studySetId'
      preLoaderRoute: typeof StudentDashboardAssignedWordsStudySetIdRouteImport
      parentRoute: typeof StudentRoute
    }
    '/m/words/personal/$personalWordSetId': {
      id: '/m/words/personal/$personalWordSetId'
      path: '/words/personal/$personalWordSetId'
      fullPath: '/m/words/personal/$personalWordSetId'
      preLoaderRoute: typeof MWordsPersonalPersonalWordSetIdRouteImport
      parentRoute: typeof MRoute
    }
    '/m/words/assigned/$studySetId': {
      id: '/m/words/assigned/$studySetId'
      path: '/words/assigned/$studySetId'
      fullPath: '/m/words/assigned/$studySetId'
      preLoaderRoute: typeof MWordsAssignedStudySetIdRouteImport
      parentRoute: typeof MRoute
    }
    '/teacher/students_/$studentId_/assigned-words/$studySetId': {
      id: '/teacher/students_/$studentId_/assigned-words/$studySetId'
      path: '/students/$studentId/assigned-words/$studySetId'
      fullPath: '/teacher/students/$studentId/assigned-words/$studySetId'
      preLoaderRoute: typeof TeacherStudentsStudentIdAssignedWordsStudySetIdRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/clinics_/students/$studentId_/personal-words/$personalWordSetId': {
      id: '/teacher/clinics_/students/$studentId_/personal-words/$personalWordSetId'
      path: '/clinics/students/$studentId/personal-words/$personalWordSetId'
      fullPath: '/teacher/clinics/students/$studentId/personal-words/$personalWordSetId'
      preLoaderRoute: typeof TeacherClinicsStudentsStudentIdPersonalWordsPersonalWordSetIdRouteImport
      parentRoute: typeof TeacherRoute
    }
  }
}

interface MRouteChildren {
  MAccountRoute: typeof MAccountRoute
  MLibraryRoute: typeof MLibraryRoute
  MUnsupportedRoute: typeof MUnsupportedRoute
  MIndexRoute: typeof MIndexRoute
  MWordsReviewRoute: typeof MWordsReviewRoute
  MWordsAssignedStudySetIdRoute: typeof MWordsAssignedStudySetIdRoute
  MWordsPersonalPersonalWordSetIdRoute: typeof MWordsPersonalPersonalWordSetIdRoute
  MWordsPersonalIndexRoute: typeof MWordsPersonalIndexRoute
}

const MRouteChildren: MRouteChildren = {
  MAccountRoute: MAccountRoute,
  MLibraryRoute: MLibraryRoute,
  MUnsupportedRoute: MUnsupportedRoute,
  MIndexRoute: MIndexRoute,
  MWordsReviewRoute: MWordsReviewRoute,
  MWordsAssignedStudySetIdRoute: MWordsAssignedStudySetIdRoute,
  MWordsPersonalPersonalWordSetIdRoute: MWordsPersonalPersonalWordSetIdRoute,
  MWordsPersonalIndexRoute: MWordsPersonalIndexRoute,
}

const MRouteWithChildren = MRoute._addFileChildren(MRouteChildren)

interface StudentRouteChildren {
  StudentDashboardRoute: typeof StudentDashboardRoute
  StudentWordTestRoute: typeof StudentWordTestRoute
  StudentIndexRoute: typeof StudentIndexRoute
  StudentDashboardPendingReviewsRoute: typeof StudentDashboardPendingReviewsRoute
  StudentPersonalWordsPersonalWordSetIdRoute: typeof StudentPersonalWordsPersonalWordSetIdRoute
  StudentReviewDeckWordsRoute: typeof StudentReviewDeckWordsRoute
  StudentLevelTestIndexRoute: typeof StudentLevelTestIndexRoute
  StudentPersonalWordsIndexRoute: typeof StudentPersonalWordsIndexRoute
  StudentReviewDeckIndexRoute: typeof StudentReviewDeckIndexRoute
  StudentDashboardAssignedWordsStudySetIdRoute: typeof StudentDashboardAssignedWordsStudySetIdRoute
  StudentLevelTestStudySetIdWordsRoute: typeof StudentLevelTestStudySetIdWordsRoute
  StudentReviewDeckStudySetIdWordsRoute: typeof StudentReviewDeckStudySetIdWordsRoute
  StudentWordTestIdWordsRoute: typeof StudentWordTestIdWordsRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentDashboardRoute: StudentDashboardRoute,
  StudentWordTestRoute: StudentWordTestRoute,
  StudentIndexRoute: StudentIndexRoute,
  StudentDashboardPendingReviewsRoute: StudentDashboardPendingReviewsRoute,
  StudentPersonalWordsPersonalWordSetIdRoute:
    StudentPersonalWordsPersonalWordSetIdRoute,
  StudentReviewDeckWordsRoute: StudentReviewDeckWordsRoute,
  StudentLevelTestIndexRoute: StudentLevelTestIndexRoute,
  StudentPersonalWordsIndexRoute: StudentPersonalWordsIndexRoute,
  StudentReviewDeckIndexRoute: StudentReviewDeckIndexRoute,
  StudentDashboardAssignedWordsStudySetIdRoute:
    StudentDashboardAssignedWordsStudySetIdRoute,
  StudentLevelTestStudySetIdWordsRoute: StudentLevelTestStudySetIdWordsRoute,
  StudentReviewDeckStudySetIdWordsRoute: StudentReviewDeckStudySetIdWordsRoute,
  StudentWordTestIdWordsRoute: StudentWordTestIdWordsRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

interface TeacherRouteChildren {
  TeacherAdminRoute: typeof TeacherAdminRoute
  TeacherClinicsRoute: typeof TeacherClinicsRoute
  TeacherGradingRoute: typeof TeacherGradingRoute
  TeacherStudentsRoute: typeof TeacherStudentsRoute
  TeacherVocabularyBankRoute: typeof TeacherVocabularyBankRoute
  TeacherIndexRoute: typeof TeacherIndexRoute
  TeacherStudentsStudentIdRoute: typeof TeacherStudentsStudentIdRoute
  TeacherClinicsStudentsStudentIdRoute: typeof TeacherClinicsStudentsStudentIdRoute
  TeacherStudentsStudentIdPendingReviewsRoute: typeof TeacherStudentsStudentIdPendingReviewsRoute
  TeacherStudentsStudentIdAssignedWordsStudySetIdRoute: typeof TeacherStudentsStudentIdAssignedWordsStudySetIdRoute
  TeacherClinicsStudentsStudentIdPersonalWordsPersonalWordSetIdRoute: typeof TeacherClinicsStudentsStudentIdPersonalWordsPersonalWordSetIdRoute
}

const TeacherRouteChildren: TeacherRouteChildren = {
  TeacherAdminRoute: TeacherAdminRoute,
  TeacherClinicsRoute: TeacherClinicsRoute,
  TeacherGradingRoute: TeacherGradingRoute,
  TeacherStudentsRoute: TeacherStudentsRoute,
  TeacherVocabularyBankRoute: TeacherVocabularyBankRoute,
  TeacherIndexRoute: TeacherIndexRoute,
  TeacherStudentsStudentIdRoute: TeacherStudentsStudentIdRoute,
  TeacherClinicsStudentsStudentIdRoute: TeacherClinicsStudentsStudentIdRoute,
  TeacherStudentsStudentIdPendingReviewsRoute:
    TeacherStudentsStudentIdPendingReviewsRoute,
  TeacherStudentsStudentIdAssignedWordsStudySetIdRoute:
    TeacherStudentsStudentIdAssignedWordsStudySetIdRoute,
  TeacherClinicsStudentsStudentIdPersonalWordsPersonalWordSetIdRoute:
    TeacherClinicsStudentsStudentIdPersonalWordsPersonalWordSetIdRoute,
}

const TeacherRouteWithChildren =
  TeacherRoute._addFileChildren(TeacherRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MRoute: MRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  PendingRoute: PendingRoute,
  StudentRoute: StudentRouteWithChildren,
  TeacherRoute: TeacherRouteWithChildren,
  OauthCallbackRoute: OauthCallbackRoute,
  StudentPersonalSelfTestPersonalWordSetIdRoute:
    StudentPersonalSelfTestPersonalWordSetIdRoute,
  StudentSelfTestStudySetIdRoute: StudentSelfTestStudySetIdRoute,
  StudentExamsExamIdReviewRoute: StudentExamsExamIdReviewRoute,
  StudentExamsExamIdTakeRoute: StudentExamsExamIdTakeRoute,
  TeacherExamsExamIdPreviewRoute: TeacherExamsExamIdPreviewRoute,
  TeacherExamsExamIdReviewRoute: TeacherExamsExamIdReviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
