/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as TeacherRouteImport } from './../routes/teacher'
import { Route as StudentRouteImport } from './../routes/student'
import { Route as IndexRouteImport } from './../routes/index'
import { Route as TeacherVocabularyBankRouteImport } from './../routes/teacher/vocabulary-bank'
import { Route as TeacherTestGradingRouteImport } from './../routes/teacher/test-grading'
import { Route as TeacherTestAssignmentRouteImport } from './../routes/teacher/test-assignment'
import { Route as TeacherPrintPreviewRouteImport } from './../routes/teacher/print-preview'
import { Route as TeacherDashboardRouteImport } from './../routes/teacher/dashboard'
import { Route as TeacherClinicRouteImport } from './../routes/teacher/clinic'
import { Route as TeacherClassRouteImport } from './../routes/teacher/class'
import { Route as StudentVocabularyRouteImport } from './../routes/student/vocabulary'
import { Route as StudentDashboardRouteImport } from './../routes/student/dashboard'
import { Route as TeacherClassIndexRouteImport } from './../routes/teacher/class/index'
import { Route as TeacherTestAssignmentStudentIdRouteImport } from './../routes/teacher/test-assignment_.$studentId'
import { Route as TeacherClassClassIdRouteImport } from './../routes/teacher/class/$classId'

const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherVocabularyBankRoute = TeacherVocabularyBankRouteImport.update({
  id: '/vocabulary-bank',
  path: '/vocabulary-bank',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherTestGradingRoute = TeacherTestGradingRouteImport.update({
  id: '/test-grading',
  path: '/test-grading',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherTestAssignmentRoute = TeacherTestAssignmentRouteImport.update({
  id: '/test-assignment',
  path: '/test-assignment',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherPrintPreviewRoute = TeacherPrintPreviewRouteImport.update({
  id: '/print-preview',
  path: '/print-preview',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherDashboardRoute = TeacherDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherClinicRoute = TeacherClinicRouteImport.update({
  id: '/clinic',
  path: '/clinic',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherClassRoute = TeacherClassRouteImport.update({
  id: '/class',
  path: '/class',
  getParentRoute: () => TeacherRoute,
} as any)
const StudentVocabularyRoute = StudentVocabularyRouteImport.update({
  id: '/vocabulary',
  path: '/vocabulary',
  getParentRoute: () => StudentRoute,
} as any)
const StudentDashboardRoute = StudentDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => StudentRoute,
} as any)
const TeacherClassIndexRoute = TeacherClassIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeacherClassRoute,
} as any)
const TeacherTestAssignmentStudentIdRoute =
  TeacherTestAssignmentStudentIdRouteImport.update({
    id: '/test-assignment_/$studentId',
    path: '/test-assignment/$studentId',
    getParentRoute: () => TeacherRoute,
  } as any)
const TeacherClassClassIdRoute = TeacherClassClassIdRouteImport.update({
  id: '/$classId',
  path: '/$classId',
  getParentRoute: () => TeacherClassRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/student': typeof StudentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/vocabulary': typeof StudentVocabularyRoute
  '/teacher/class': typeof TeacherClassRouteWithChildren
  '/teacher/clinic': typeof TeacherClinicRoute
  '/teacher/dashboard': typeof TeacherDashboardRoute
  '/teacher/print-preview': typeof TeacherPrintPreviewRoute
  '/teacher/test-assignment': typeof TeacherTestAssignmentRoute
  '/teacher/test-grading': typeof TeacherTestGradingRoute
  '/teacher/vocabulary-bank': typeof TeacherVocabularyBankRoute
  '/teacher/class/$classId': typeof TeacherClassClassIdRoute
  '/teacher/test-assignment/$studentId': typeof TeacherTestAssignmentStudentIdRoute
  '/teacher/class/': typeof TeacherClassIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/student': typeof StudentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/vocabulary': typeof StudentVocabularyRoute
  '/teacher/clinic': typeof TeacherClinicRoute
  '/teacher/dashboard': typeof TeacherDashboardRoute
  '/teacher/print-preview': typeof TeacherPrintPreviewRoute
  '/teacher/test-assignment': typeof TeacherTestAssignmentRoute
  '/teacher/test-grading': typeof TeacherTestGradingRoute
  '/teacher/vocabulary-bank': typeof TeacherVocabularyBankRoute
  '/teacher/class/$classId': typeof TeacherClassClassIdRoute
  '/teacher/test-assignment/$studentId': typeof TeacherTestAssignmentStudentIdRoute
  '/teacher/class': typeof TeacherClassIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/student': typeof StudentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/vocabulary': typeof StudentVocabularyRoute
  '/teacher/class': typeof TeacherClassRouteWithChildren
  '/teacher/clinic': typeof TeacherClinicRoute
  '/teacher/dashboard': typeof TeacherDashboardRoute
  '/teacher/print-preview': typeof TeacherPrintPreviewRoute
  '/teacher/test-assignment': typeof TeacherTestAssignmentRoute
  '/teacher/test-grading': typeof TeacherTestGradingRoute
  '/teacher/vocabulary-bank': typeof TeacherVocabularyBankRoute
  '/teacher/class/$classId': typeof TeacherClassClassIdRoute
  '/teacher/test-assignment_/$studentId': typeof TeacherTestAssignmentStudentIdRoute
  '/teacher/class/': typeof TeacherClassIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/student'
    | '/teacher'
    | '/student/dashboard'
    | '/student/vocabulary'
    | '/teacher/class'
    | '/teacher/clinic'
    | '/teacher/dashboard'
    | '/teacher/print-preview'
    | '/teacher/test-assignment'
    | '/teacher/test-grading'
    | '/teacher/vocabulary-bank'
    | '/teacher/class/$classId'
    | '/teacher/test-assignment/$studentId'
    | '/teacher/class/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/student'
    | '/teacher'
    | '/student/dashboard'
    | '/student/vocabulary'
    | '/teacher/clinic'
    | '/teacher/dashboard'
    | '/teacher/print-preview'
    | '/teacher/test-assignment'
    | '/teacher/test-grading'
    | '/teacher/vocabulary-bank'
    | '/teacher/class/$classId'
    | '/teacher/test-assignment/$studentId'
    | '/teacher/class'
  id:
    | '__root__'
    | '/'
    | '/student'
    | '/teacher'
    | '/student/dashboard'
    | '/student/vocabulary'
    | '/teacher/class'
    | '/teacher/clinic'
    | '/teacher/dashboard'
    | '/teacher/print-preview'
    | '/teacher/test-assignment'
    | '/teacher/test-grading'
    | '/teacher/vocabulary-bank'
    | '/teacher/class/$classId'
    | '/teacher/test-assignment_/$studentId'
    | '/teacher/class/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StudentRoute: typeof StudentRouteWithChildren
  TeacherRoute: typeof TeacherRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/vocabulary-bank': {
      id: '/teacher/vocabulary-bank'
      path: '/vocabulary-bank'
      fullPath: '/teacher/vocabulary-bank'
      preLoaderRoute: typeof TeacherVocabularyBankRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/test-grading': {
      id: '/teacher/test-grading'
      path: '/test-grading'
      fullPath: '/teacher/test-grading'
      preLoaderRoute: typeof TeacherTestGradingRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/test-assignment': {
      id: '/teacher/test-assignment'
      path: '/test-assignment'
      fullPath: '/teacher/test-assignment'
      preLoaderRoute: typeof TeacherTestAssignmentRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/print-preview': {
      id: '/teacher/print-preview'
      path: '/print-preview'
      fullPath: '/teacher/print-preview'
      preLoaderRoute: typeof TeacherPrintPreviewRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/dashboard': {
      id: '/teacher/dashboard'
      path: '/dashboard'
      fullPath: '/teacher/dashboard'
      preLoaderRoute: typeof TeacherDashboardRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/clinic': {
      id: '/teacher/clinic'
      path: '/clinic'
      fullPath: '/teacher/clinic'
      preLoaderRoute: typeof TeacherClinicRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/class': {
      id: '/teacher/class'
      path: '/class'
      fullPath: '/teacher/class'
      preLoaderRoute: typeof TeacherClassRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/student/vocabulary': {
      id: '/student/vocabulary'
      path: '/vocabulary'
      fullPath: '/student/vocabulary'
      preLoaderRoute: typeof StudentVocabularyRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/dashboard': {
      id: '/student/dashboard'
      path: '/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof StudentDashboardRouteImport
      parentRoute: typeof StudentRoute
    }
    '/teacher/class/': {
      id: '/teacher/class/'
      path: '/'
      fullPath: '/teacher/class/'
      preLoaderRoute: typeof TeacherClassIndexRouteImport
      parentRoute: typeof TeacherClassRoute
    }
    '/teacher/test-assignment_/$studentId': {
      id: '/teacher/test-assignment_/$studentId'
      path: '/test-assignment/$studentId'
      fullPath: '/teacher/test-assignment/$studentId'
      preLoaderRoute: typeof TeacherTestAssignmentStudentIdRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/class/$classId': {
      id: '/teacher/class/$classId'
      path: '/$classId'
      fullPath: '/teacher/class/$classId'
      preLoaderRoute: typeof TeacherClassClassIdRouteImport
      parentRoute: typeof TeacherClassRoute
    }
  }
}

interface StudentRouteChildren {
  StudentDashboardRoute: typeof StudentDashboardRoute
  StudentVocabularyRoute: typeof StudentVocabularyRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentDashboardRoute: StudentDashboardRoute,
  StudentVocabularyRoute: StudentVocabularyRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

interface TeacherClassRouteChildren {
  TeacherClassClassIdRoute: typeof TeacherClassClassIdRoute
  TeacherClassIndexRoute: typeof TeacherClassIndexRoute
}

const TeacherClassRouteChildren: TeacherClassRouteChildren = {
  TeacherClassClassIdRoute: TeacherClassClassIdRoute,
  TeacherClassIndexRoute: TeacherClassIndexRoute,
}

const TeacherClassRouteWithChildren = TeacherClassRoute._addFileChildren(
  TeacherClassRouteChildren,
)

interface TeacherRouteChildren {
  TeacherClassRoute: typeof TeacherClassRouteWithChildren
  TeacherClinicRoute: typeof TeacherClinicRoute
  TeacherDashboardRoute: typeof TeacherDashboardRoute
  TeacherPrintPreviewRoute: typeof TeacherPrintPreviewRoute
  TeacherTestAssignmentRoute: typeof TeacherTestAssignmentRoute
  TeacherTestGradingRoute: typeof TeacherTestGradingRoute
  TeacherVocabularyBankRoute: typeof TeacherVocabularyBankRoute
  TeacherTestAssignmentStudentIdRoute: typeof TeacherTestAssignmentStudentIdRoute
}

const TeacherRouteChildren: TeacherRouteChildren = {
  TeacherClassRoute: TeacherClassRouteWithChildren,
  TeacherClinicRoute: TeacherClinicRoute,
  TeacherDashboardRoute: TeacherDashboardRoute,
  TeacherPrintPreviewRoute: TeacherPrintPreviewRoute,
  TeacherTestAssignmentRoute: TeacherTestAssignmentRoute,
  TeacherTestGradingRoute: TeacherTestGradingRoute,
  TeacherVocabularyBankRoute: TeacherVocabularyBankRoute,
  TeacherTestAssignmentStudentIdRoute: TeacherTestAssignmentStudentIdRoute,
}

const TeacherRouteWithChildren =
  TeacherRoute._addFileChildren(TeacherRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StudentRoute: StudentRouteWithChildren,
  TeacherRoute: TeacherRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
