/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as TeacherRouteImport } from './../routes/teacher'
import { Route as StudentRouteImport } from './../routes/student'
import { Route as IndexRouteImport } from './../routes/index'
import { Route as TeacherVocabularyBankRouteImport } from './../routes/teacher/vocabulary-bank'
import { Route as TeacherTestGradingRouteImport } from './../routes/teacher/test-grading'
import { Route as TeacherTestAssignmentRouteImport } from './../routes/teacher/test-assignment'
import { Route as StudentVocabularyRouteImport } from './../routes/student/vocabulary'
import { Route as StudentDashboardRouteImport } from './../routes/student/dashboard'
import { Route as TeacherTestAssignmentStudentIdRouteImport } from './../routes/teacher/test-assignment_.$studentId'

const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherVocabularyBankRoute = TeacherVocabularyBankRouteImport.update({
  id: '/vocabulary-bank',
  path: '/vocabulary-bank',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherTestGradingRoute = TeacherTestGradingRouteImport.update({
  id: '/test-grading',
  path: '/test-grading',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherTestAssignmentRoute = TeacherTestAssignmentRouteImport.update({
  id: '/test-assignment',
  path: '/test-assignment',
  getParentRoute: () => TeacherRoute,
} as any)
const StudentVocabularyRoute = StudentVocabularyRouteImport.update({
  id: '/vocabulary',
  path: '/vocabulary',
  getParentRoute: () => StudentRoute,
} as any)
const StudentDashboardRoute = StudentDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => StudentRoute,
} as any)
const TeacherTestAssignmentStudentIdRoute =
  TeacherTestAssignmentStudentIdRouteImport.update({
    id: '/test-assignment_/$studentId',
    path: '/test-assignment/$studentId',
    getParentRoute: () => TeacherRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/student': typeof StudentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/vocabulary': typeof StudentVocabularyRoute
  '/teacher/test-assignment': typeof TeacherTestAssignmentRoute
  '/teacher/test-grading': typeof TeacherTestGradingRoute
  '/teacher/vocabulary-bank': typeof TeacherVocabularyBankRoute
  '/teacher/test-assignment/$studentId': typeof TeacherTestAssignmentStudentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/student': typeof StudentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/vocabulary': typeof StudentVocabularyRoute
  '/teacher/test-assignment': typeof TeacherTestAssignmentRoute
  '/teacher/test-grading': typeof TeacherTestGradingRoute
  '/teacher/vocabulary-bank': typeof TeacherVocabularyBankRoute
  '/teacher/test-assignment/$studentId': typeof TeacherTestAssignmentStudentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/student': typeof StudentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/vocabulary': typeof StudentVocabularyRoute
  '/teacher/test-assignment': typeof TeacherTestAssignmentRoute
  '/teacher/test-grading': typeof TeacherTestGradingRoute
  '/teacher/vocabulary-bank': typeof TeacherVocabularyBankRoute
  '/teacher/test-assignment_/$studentId': typeof TeacherTestAssignmentStudentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/student'
    | '/teacher'
    | '/student/dashboard'
    | '/student/vocabulary'
    | '/teacher/test-assignment'
    | '/teacher/test-grading'
    | '/teacher/vocabulary-bank'
    | '/teacher/test-assignment/$studentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/student'
    | '/teacher'
    | '/student/dashboard'
    | '/student/vocabulary'
    | '/teacher/test-assignment'
    | '/teacher/test-grading'
    | '/teacher/vocabulary-bank'
    | '/teacher/test-assignment/$studentId'
  id:
    | '__root__'
    | '/'
    | '/student'
    | '/teacher'
    | '/student/dashboard'
    | '/student/vocabulary'
    | '/teacher/test-assignment'
    | '/teacher/test-grading'
    | '/teacher/vocabulary-bank'
    | '/teacher/test-assignment_/$studentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StudentRoute: typeof StudentRouteWithChildren
  TeacherRoute: typeof TeacherRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/vocabulary-bank': {
      id: '/teacher/vocabulary-bank'
      path: '/vocabulary-bank'
      fullPath: '/teacher/vocabulary-bank'
      preLoaderRoute: typeof TeacherVocabularyBankRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/test-grading': {
      id: '/teacher/test-grading'
      path: '/test-grading'
      fullPath: '/teacher/test-grading'
      preLoaderRoute: typeof TeacherTestGradingRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/test-assignment': {
      id: '/teacher/test-assignment'
      path: '/test-assignment'
      fullPath: '/teacher/test-assignment'
      preLoaderRoute: typeof TeacherTestAssignmentRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/student/vocabulary': {
      id: '/student/vocabulary'
      path: '/vocabulary'
      fullPath: '/student/vocabulary'
      preLoaderRoute: typeof StudentVocabularyRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/dashboard': {
      id: '/student/dashboard'
      path: '/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof StudentDashboardRouteImport
      parentRoute: typeof StudentRoute
    }
    '/teacher/test-assignment_/$studentId': {
      id: '/teacher/test-assignment_/$studentId'
      path: '/test-assignment/$studentId'
      fullPath: '/teacher/test-assignment/$studentId'
      preLoaderRoute: typeof TeacherTestAssignmentStudentIdRouteImport
      parentRoute: typeof TeacherRoute
    }
  }
}

interface StudentRouteChildren {
  StudentDashboardRoute: typeof StudentDashboardRoute
  StudentVocabularyRoute: typeof StudentVocabularyRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentDashboardRoute: StudentDashboardRoute,
  StudentVocabularyRoute: StudentVocabularyRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

interface TeacherRouteChildren {
  TeacherTestAssignmentRoute: typeof TeacherTestAssignmentRoute
  TeacherTestGradingRoute: typeof TeacherTestGradingRoute
  TeacherVocabularyBankRoute: typeof TeacherVocabularyBankRoute
  TeacherTestAssignmentStudentIdRoute: typeof TeacherTestAssignmentStudentIdRoute
}

const TeacherRouteChildren: TeacherRouteChildren = {
  TeacherTestAssignmentRoute: TeacherTestAssignmentRoute,
  TeacherTestGradingRoute: TeacherTestGradingRoute,
  TeacherVocabularyBankRoute: TeacherVocabularyBankRoute,
  TeacherTestAssignmentStudentIdRoute: TeacherTestAssignmentStudentIdRoute,
}

const TeacherRouteWithChildren =
  TeacherRoute._addFileChildren(TeacherRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StudentRoute: StudentRouteWithChildren,
  TeacherRoute: TeacherRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
